### ISSUE TITLE
Collectd in influxdb

### ISSUE THREAD

**Issue by yeyeoke** [hassio-addons/addon-influxdb#1]
# Problem/Motivation
Influxdb needs a simple change to the configuration to be able to collect data from collectd as far as I can tell atleast, but since I'm new to both influxdb and grafana, I'm open to the possibility that I'm wrong. 

## Proposed changes
While reading this guide https://anomaly.io/collectd-metrics-to-influxdb/
it seems that the only change needed is; 

```
[collectd]
enabled = true
port = 25826
database = "collectd_db"
typesdb = "/opt/collectd/share/collectd/types.db"

```
Great work with the addon I'm really enjoying it. 

<blockquote><img src="https://anomaly.io/wp-content/uploads/2015/04/collectd-to-influxdb.png" width="48" align="right"><div>Anomaly</div><div><strong><a href="https://anomaly.io/collectd-metrics-to-influxdb/">Sending CollectD Metrics to InfluxDB - Anomaly</a></strong></div><div>Configuration example to send metrics from Collectd to InfluxDB. Then, configure InfluxDB to receive Collectd metrics. Enjoy your new monitoring dashboard</div></blockquote>

**Comment by tremebundo** [comment]
Any news with this?
It should be great to get collectd integrated with this Inluxdb instance and displayed in Home Assistant with your Grafana addon.
Thanks a lot for your work.

**Comment by frenck** [comment]
@tremebundo @yeyeoke 
I've actually built the feature and it is currently living is a separate branch on my development machine.

I'm not sure if I should publish it though. It seems to be a pretty edge case. Maybe I'm just not too familiar with all this, but as far as I understand, I'd would need collectd itself as well.

Is this correct? Our would simply open up Collectd in Influx be enough?
Could you guys provide me some hint on how to test and/or set this thing up?

**Comment by tremebundo** [comment]
Ufff!
I am pretty new to collectd and Influxdb.
I have just installed the official package of collectd in a Ubuntu 16.04. I am running Hassio in a docker container with your Inluxdb and Grafana plugins. Collectd seems to be already collecting data.
Now I need to display its data some way and I thought using your plugins and have a panel frame in Home Assistant.
I am trying to follow this guide:

https://www.buffalodatasystems.com/2017/10/24/Getting-started-with-grafana-and-ubuntu-16-04/

But I thought about using the Inluxdb instance provided by your plugin to avoid installing another Influxdb on the host system.
My server is hanging up randomly and I think some persistent statistics would help me to address the problem. And I think also that having that data displayed on a healthy system through HA would be very convenient. 
Sorry for not being very helpful.

**Comment by frenck** [comment]
@yeyeoke, as the original requester; Do you have any pointers for me?

**Comment by frenck** [comment]
https://community.home-assistant.io/t/community-hass-io-add-on-influxdb/54491/60?u=frenck

![image](https://user-images.githubusercontent.com/195327/41997916-b17e2eac-7a59-11e8-8f69-c15ef329dd6d.png)

**Comment by frenck** [comment]
Close this feature request, since it seems to me a very tiny use-case.
Telegraf might be something to consider 😉
