### ISSUE TITLE
Password using !secret cannot be saved

### ISSUE THREAD

**Issue by doschi** [hassio-addons/addon-influxdb#10]
# Problem/Motivation

I try to use !secret in the configuration, but the configuration cannot be saved

## Expected behavior

i can add the following line for passwords
` "password": !secret influx_password,`

## Actual behavior

The editor doesn't allow me to save the configuration (Config marked red, save disabled)

## Steps to reproduce

`{
  "log_level": "info",
  "username": "someuser",
  "password": !secret influx_password,
  "auth": true,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "ipv6": false
}`

**Comment by tjorim** [comment]
The configuration of add-ons is Json-formatted, which doesn't work like that. Put `"!secret influx_password"` between quotes.
When having problems like this, try to check your config with a JSON validator like this: https://jsonlint.com

**Comment by frenck** [comment]
That is indeed invalid JSON, and @tjorim provided the correct answer.
Closing this issue.
