### ISSUE TITLE
sensors unavailable at HA startup are counted...

### ISSUE THREAD

**Issue by JohannCR** [hassio-addons/addon-influxdb#100]
Hi,
I'm having trouble when I graph binary sensors using grafana on influxdb because it marks a change of state at each reboot of HA.
I know that template binary sensors are unavailable during HA startup, but 
1°) these are not template, so I don't understand why they are affected
2°) is there a way to counter this behaviour ? Like “pausing” influxdb until all sensors are ok ?
Or can we modify the query so that it only counts changes of states not linked to a reboot ?
Or is it possible to delete all entries in influxdb that coincide with a startup and how ?

**Comment by frenck** [comment]
Hi there,

Thanks for opening an issue. This is not an issue with the add-on, but quite possibly with the Home Assistant integration for InfluxDB. Please report your issue with the Home Assistant project.

From the add-on side of things, there is nothing I can do about it.
