### ISSUE TITLE
cannot install influxdb

### ISSUE THREAD

**Issue by mbaluda** [hassio-addons/addon-influxdb#106]
# Problem/Motivation

Influx would not install cleanly

## Actual behavior

500 Server Error for http+docker://localhost/v1.40/images/hassioaddons/influxdb-armv7:3.7.9/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")

**Comment by frenck** [comment]
`500 Server Error for http+docker://localhost/v1.40/images/hassioaddons/influxdb-armv7:3.7.9/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")`

That is an issue with your system and not the add-on. From the add-on perspective, there is nothing I can do.

You can try running an `ha supervisor repair` from the CLI and also, make sure you are on the latest HassOS (if that applies to you).

If the problem persists, please raise an issue with the Home Assistant team.
