### ISSUE TITLE
Unable to parse authentication credentials

### ISSUE THREAD

**Issue by ast0815** [hassio-addons/addon-influxdb#111]
# Problem/Motivation

I am trying to get the InfluxDB going with my raspberry pi install of home assistant

## Expected behavior

I want to start recording state changes in the DB.

## Actual behavior

When following the documentation and trying to add a new database, I get an error message about an authentication error.

```
time="2021-01-23T11:19:35Z" level=error msg="Error message received status code 401 from server: err: unable to parse authentication credentials" component=server http_status =400
time="2021-01-23T11:19:35Z" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:48044" response_time=5.721519ms status=400
```

## Steps to reproduce

Click on "OPEN WEB UI" to open the admin web-interface provided by this add-on.
On the left menu click on the "InfluxDB Admin".
Create a database for storing Home Assistant's data in, e.g., homeassistant.

Do I have to create a user or some sort of login details for this to work? I did not find something like that in the documentation...

**Comment by frenck** [comment]
Fixed in #110
