### ISSUE TITLE
default_measurement option gives warning in HA 2021.2.2

### ISSUE THREAD

**Issue by poudenes** [hassio-addons/addon-influxdb#129]
# Problem/Motivation

InfluxDB have a option `default_measurement` but it gives a warning in de supervisor log

## Expected behavior

Don't know. Or the option is not in use anymore. But how can you config the measurement to state for example

## Actual behavior

Addon is working normal, but you see those warnings in the log

## Steps to reproduce

Install the add-on and add the option `default_measurement` into the config.

## log info

21-02-09 14:54:38 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement
21-02-09 14:55:38 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement
21-02-09 14:56:38 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement
21-02-09 14:57:38 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement
21-02-09 14:58:38 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement
21-02-09 14:59:00 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement
21-02-09 14:59:38 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement
21-02-09 15:00:14 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement
21-02-09 15:00:38 WARNING (MainThread) [supervisor.addons.options] Unknown options default_measurement

**Comment by sinclairpaul** [comment]
I think you are confusing the options for the addon with that of the integration.  It is not a valid addon configuration option, as per the error and should be removed from your config.

Further information on the integration can be seen at:

https://www.home-assistant.io/integrations/influxdb/

**Comment by poudenes** [comment]
I see it now.. my fault !!! Sorry!!!
