### ISSUE TITLE
InfluxDB and Grafana not receiving sensor data from Home Assistant

### ISSUE THREAD

**Issue by tgduffy** [hassio-addons/addon-influxdb#132]
# Problem/Motivation

> (Why the issue was filed)   _
InfluxDB and Grafana not receiving sensor data from Home Assistant_

## Expected behavior

> (What you expected to happen) 
InfluxDB and Grafana to receive sensor data. I saved and tested after Grafana installation and got confirmation that data sources working.

## Actual behavior

> (What actually happened) 
InfluxDB and Grafana, not receive sensor data

## Steps to reproduce

> (How can someone else make/see it happen) 
I don't know!

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)  
If somebody has encountered this problem previously, they may be able to point me towards a solution.

**Comment by frenck** [comment]
How have you set up and configured Home Assistant?

**Comment by tgduffy** [comment]
Thank you very much for responding. I downloaded from Home Assistant, etched using Balena and installed on Raspberry Pi 4B. This is my second installation as the Raspberry Pi went off-line about a week ago. I had the sensor data flowing to Influx DB and Grafana on my earlier identical installation. I have watched several YouTube videos and have rigidly followed the steps.

**Comment by frenck** [comment]
That is nice, but... That didn't answer my question 🤷‍♂️

**Comment by tgduffy** [comment]
![tgd1](https://user-images.githubusercontent.com/50514240/107889599-b4963b80-6f0b-11eb-9012-895f194997a5.PNG)

Does this make my configuration any clearer? I am using Windows 10, if that is of any relevance.

**Comment by tgduffy** [comment]
![tgd2](https://user-images.githubusercontent.com/50514240/107889748-954bde00-6f0c-11eb-857a-4625d3044920.PNG)

All of my sensors are working fine in Overview/Lovelace.


Config.yaml below

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Unflashed SONOFF devices
sonoff:
  username: tom@dce.ie
  password: inniskeen
  reload: always
  
  # Meross
  
  meross_cloud:
    username: tom@dce.ie
    password: inniskeen
    
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: <1234>
  max_retries: 3
  default_measurement: state

**Comment by tgduffy** [comment]
![tgd3](https://user-images.githubusercontent.com/50514240/107890050-91b95680-6f0e-11eb-9974-166ce801d06c.PNG)







[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 4.0.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.11  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.9
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] create-users.sh: executing... 
[cont-init.d] create-users.sh: exited 0.
[cont-init.d] influxdb.sh: executing... 
[cont-init.d] influxdb.sh: exited 0.
[cont-init.d] kapacitor.sh: executing... 
[cont-init.d] kapacitor.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:43:58] INFO: Kapacitor is waiting until InfluxDB is available...
[21:43:58] INFO: Chronograf is waiting until InfluxDB is available...
[21:43:58] INFO: Starting the InfluxDB...

**Comment by tgduffy** [comment]
The items outlined in red below I entered manually as no sensor data was available from the drop down menus.



![tgd4](https://user-images.githubusercontent.com/50514240/107890174-4e131c80-6f0f-11eb-956b-78d3be30985e.PNG)

**Comment by tgduffy** [comment]
I see that I am not alone!
![tgd5](https://user-images.githubusercontent.com/50514240/108107250-e5e74680-7086-11eb-91f9-12ec9742b425.PNG)

For some reason, sensor data is not coming through to Influx DB.
![image](https://user-images.githubusercontent.com/50514240/108107714-80478a00-7087-11eb-9541-d9846df056d4.png)

**Comment by tgduffy** [comment]
I finally got this sorted out. In the configuration.yaml file for InfluxDB, my password was enclosed in <....> brackets. Removing those seems to have solved the problem. Again, every day is a school day!

**Comment by frenck** [comment]
Oh shit haha! Well, that happens! Glad you got it resolved 👍
