### ISSUE TITLE
HA send all fields of device instead of just entity

### ISSUE THREAD

**Issue by abneits** [hassio-addons/addon-influxdb#134]
# Problem/Motivation

A lot of useless data are imported. 
My DB grow up with 90% useless data.

## Expected behavior

HA send only the entity that i want, not all related entities of this device

## Actual behavior

When i put in my config file in include / entities / sensor.capteur_temperature_exterieur_temperature for example.
All of the related entities all also import.

![image](https://user-images.githubusercontent.com/48256206/107982213-ec60ba00-6fc3-11eb-8ec8-54915fefa5e2.png)

## Steps to reproduce
my config file :  
  host: XXX.XXX.XXX.XXX
  port: XXXX
  database: XXX
  username: XXX
  password: XXX
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - sensor.capteur_temperature_exterieur_temperature
  component_config_glob:
    sensor.*temperature:
      override_measurement: temperature

## Proposed changes

Only import the value of the given entity

**Comment by frenck** [comment]
This is the InfluxDB add-on. It runs InfluxDB. If you have questions or issue with Home Assistant, please report it with Home Assistant iself. Thanks 👍
