### ISSUE TITLE
Envvars values should always be strings - Suggested clarification in documentation

### ISSUE THREAD

**Issue by michaelpiron** [hassio-addons/addon-influxdb#139]
# Problem/Motivation

It took me a bit of time to figure out that when setting environment variables in the add-on configuration, their value should always be a string, even if the variable is type boolean false/true.
This is different than other parameters in the configuration file, like _auth_, _reporting_, _ssl_. They should get boolean values.

This is illustrated here:
![image](https://user-images.githubusercontent.com/4469877/109293007-824ddd80-782b-11eb-9bef-bb98cb2e20bb.png)

I figured this out by looking at the _config.json_ file in the repository:
https://github.com/hassio-addons/addon-influxdb/blob/main/influxdb/config.json
![image](https://user-images.githubusercontent.com/4469877/109293272-d8bb1c00-782b-11eb-81c2-a3faccd51f5f.png)

## Actual behavior

Actual documentation:
![image](https://user-images.githubusercontent.com/4469877/109292949-6c401d00-782b-11eb-8317-a1c9fc7a5eb2.png)

## Steps to reproduce

In Supervisor, go to the InfluxDB add-on, and enter the configuration tab. There, if you enter environment variables' value as a boolean (true/false) you get error message.

## Proposed changes

My suggestion is to add in the add-on documentation that environment variables values should always be in string format.

**Comment by sinclairpaul** [comment]
I would suggest raising a PR for it, you should even be able to do it online with Github.

**Comment by michaelpiron** [comment]
Hi Paul,
OK, I made a pull request: https://github.com/hassio-addons/addon-influxdb/pull/140
My first pull request ever :-).
