### ISSUE TITLE
Unable to expose port 2003

### ISSUE THREAD

**Issue by mouldybread** [hassio-addons/addon-influxdb#141]
# Problem/Motivation

I want to feed graphite data into influxdb from another host.

I have successfully enabled the influxdb graphite plugin using environmental variables. 

I can see influxdb listening on 127.0.0.1:2003 within the container.

However running the docker port command shows only port 8086 mapped.

On the add on configuration page, the port is not shown in the network section. I seem to be unable to expose it.

## Expected behavior

Port shown as an option underneath 80/tcp and 8086/tcp in the Network section of the configuration tab.

## Actual behavior

Port not shown

## Steps to reproduce

Specify the relevant environmental variables as per https://docs.influxdata.com/influxdb/v1.7/administration/config/#configuration-settings

Confirm that influxdb is listening on 2003

## Proposed changes

I understand that the supervisor is Docker running in host=net mode, so i'm assuming the ports on the Configuration page are pulled from the config file. It would seem then that adding port 2003 to the config file should resolve this issue.

**Comment by frenck** [comment]
More information can be found in many more past issues and PRs. Not planning on adding it.

**Comment by mouldybread** [comment]
I could not find any related pull requests. The only related issue I could find was:
https://github.com/hassio-addons/addon-influxdb/issues/24

The issue in #24 is different can be handled with environmental variables.

The only change needed would be to provide the option to expose the port. The documentation for V2 still clearly suggests continued support for the Graphite plugin.

In my case I am using Freenas to manage storage. Freenas ships supporting Graphite. It is possible to run telegraf but this is a bit of a fudge. HA does not have a graphite addon. Given the constraints, feeding the graphite data into my HA influx instance is desirable to minimize complexity. 

The alternatives are both ugly: a separate instance of influx, or strapping the telegraf binary to freenas.

Given that handling graphite input is an official feature of influxdb it would seem that this addon should consequently support it, no? Especially if all it needs is the option for a use to expose the port.
