### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by MattyBoy4444** [hassio-addons/addon-influxdb#147]
# Problem/Motivation

SSL support is a requirement for our needs

## Proposed changes

Reimplement the changes that were removed with https://github.com/hassio-addons/addon-influxdb/commit/a7588131e512061d91328e6d95d26e81c4d92b77

I have read you are working on 2.0 implementation, but it seems it isn't coming anytime soon.  What was the problem with Chorograf and SSL support?

**Comment by frenck** [comment]
Issues are for reporting issues, not feature requests. Thanks.

**Comment by MattyBoy4444** [comment]
Wow.  I was just asking about a previous bug/issue fix and the reason why.  The changeset description is very vague.  I can make my own changes, just wondering what the Chorograf issue was.

**Comment by frenck** [comment]
Not working correctly in ssl. As per commit description.

**Comment by MattyBoy4444** [comment]
Ingress is great if all you want to use is the GUI.   I would like to get at data directly from InfluxDB.  Sorry, "not working correctly" is not a great and vague commit message.  Just saying.  It doesn't help anyone but yourself.  Wonder about that after 3 years.  I'll figure it out.  Thanks.

**Comment by frenck** [comment]
> is not a great and vague commit message

I think it is perfectly fine. I'm sure you will do better 👍
