### ISSUE TITLE
Some configuration doesn't apply

### ISSUE THREAD

**Issue by golddragon007** [hassio-addons/addon-influxdb#164]
# Problem/Motivation

I tried to disable reporting and I can't, even if I set `reporting: false`.
I see this in my log:
```
ts=2021-05-14T23:16:36.460+02:00 lvl=error msg="error while sending usage report on startup" service=reporting err="Post \"https://usage.influxdata.com/api/v1/usage/kapacitor\": dial tcp 0.0.0.0:443: connect: connection refused"
time="2021-05-14T23:17:03+02:00" level=info msg="Reporting usage stats" component=usage freq=24h 
```
I have also high usage of CPU so I tried to set some environment variables to mitigate that issue, however, it doesn't matter what I set, it seems it doesn't get applied. I tried to set INFLUXDB_MONITOR_STORE_ENABLED, but it doesn't applied on the container nor inside the container.
And I'm not sure if the `ssl` option is also working or not.

## Expected behavior

It should disable reporting.
It should set the env variable.

## Actual behavior

Doesn't do it.

## Steps to reproduce
Add to config.
```
reporting: false
envvars:
  - name: INFLUXDB_MONITOR_STORE_ENABLED
    value: 'false'
```
Block reporting dns -> you will get an error in logs (see above).
Go to portainer (or other method) find influxdb image and check if there's the added variable name (for me doesn't exist)
Go into the container and give the echo $INFLUXDB_MONITOR_STORE_ENABLED command. It will return nothing as it's not set.

## Proposed changes

Fix.

**Comment by sinclairpaul** [comment]
#145

Kapacitor config is separate to Influx, we should possibly add that flag as well.

Due to the way s6 works, I doubt you will see the env vars,

**Comment by golddragon007** [comment]
And how can I make sure that the settings are actually applied? Because when I start this addon I will have high CPU usage. and I mean from 10-20% goes up to 70-90% on all cores. I need to do something against this.

**Comment by frenck** [comment]
> And how can I make sure that the settings are actually applied?

They are applies correctly

> Because when I start this addon I will have high CPU usage.

That is not related to this change.
