### ISSUE TITLE
SSL for InfluxDB

### ISSUE THREAD

**Issue by 1MRB** [hassio-addons/addon-influxdb#17]
# Problem/Motivation

> I have external pages that are SSL querying a non-SSL InfluxDB and it is causing a mixed content error in the browser. This is mentioned in the read me that the SSL config parameter does NOT activate SSL for InfluxDB, just the web interface. I need SSL for InfluxDB.

## Expected behavior

> HTTPS request directly to the InfluxDB 

## Actual behavior

> Only supports HTTP 

## Steps to reproduce

> Queries over HTTPS are not processed.

## Proposed changes

>Tried to add the mentioned config into the config file but it keep removing it as the add-on doesn't properly read the new parameters. if this is exposed to the config then maybe it will allow the SSL on the DB side to work.
https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/

**Comment by frenck** [comment]
As mentioned in the documentation, it is not available due to technical issues in the InfluxData software.
There is nowhere I can go with this issue.

**Comment by 1MRB** [comment]
But it looks like in version 1.7 it is supported per this document. Am I missing something?
https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/
