### ISSUE TITLE
Add-on not showing up on my Home Assistant Add-on store.

### ISSUE THREAD

**Issue by Seba-VT** [hassio-addons/addon-influxdb#176]
# Problem/Motivation

I would like to install InfluxDB to try Grafana, but the Add-on is not showing up on the store. And is not adding the repository manually.

## Expected behavior

I expect the add-on to show up on the store to be able to install it.

## Actual behavior

The add no is not in the store
![image](https://user-images.githubusercontent.com/67033534/120926972-2ce85e80-c6ad-11eb-9e6c-8f13e055afa9.png)

and it wont aloud to manually add it.
![image](https://user-images.githubusercontent.com/67033534/120926897-d11dd580-c6ac-11eb-8eb9-55219acfebcd.png)

**Comment by sinclairpaul** [comment]
The Community repo is https://github.com/hassio-addons/repository
