### ISSUE TITLE
snapshot with influxdb takes hours

### ISSUE THREAD

**Issue by repiuk** [hassio-addons/addon-influxdb#179]
# Problem/Motivation
Creating a snapshot image with influxdb included takes 2 or more hours. Excluding influxdb (partial snapshot) runs normally and finishes in app. 15 minutes.
A snapshot without influxdb is app 3-4 Gb smaller.
Maybe I need to prune my influxdb but I need most of the data and never discovered how to prune specific records in influxdb

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi here @repiuk! 👋 

Yes, much data can take longer to backup. That depends on the device speed, storage speed and amount of data stored.

I'm not sure what the add-on issue is you are trying to report?

../Frenck

**Comment by repiuk** [comment]
The issue or question is how to manage the size of the influxdb database, I have no idea how to do that (except pruning the complete database). Some data I want to keep forever. Other data could be trimmed. If it keeps growing it would take many more hours for a snapshot to finish.

**Comment by frenck** [comment]
That is not an add-on issue 🤷 

You have a question on how InfluxDB or Home Assistant works...

For information on configuring Home Assistant's InfluxDB integration see:

<https://www.home-assistant.io/integrations/influxdb>

That page contains information on e.g., filtering which entities or which attributes end up in InfluxDB to limit the amount of data you send into InfluxDB to begin with.

From the InluxDB side of thing, you might want to read into setting up retentions and continuous queries to downsample your data for longer-term storage.
