### ISSUE TITLE
Disable reporting of usage metrics

### ISSUE THREAD

**Issue by niemyjski** [hassio-addons/addon-influxdb#18]
I noticed the following on startup. It would be great to opt out of usage reporting as I don't want this data leaving my network (yes I know I can add a firewall rule).
```
time="2019-01-30T08:30:39-06:00" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime" 
```

**Comment by frenck** [comment]
Good suggestion! Thanks!

**Comment by frenck** [comment]
Implemented and will be part of the next release.
