### ISSUE TITLE
after updating to 1.3.0 - all user config was lost.

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-influxdb#19]
# Problem/Motivation

lost all users configuration , so influx DB no longer works with Grafana 

## Expected behavior

as allways keep the latest config 

## Actual behavior

empty users list .

## Steps to reproduce

just update

NOTE:  i have two hassio instances on 2 vms, this happens in one of them and i had to  reload the Idb snapshot to make it work again, but on the other vm, the users were preserved after the update, so not really sure , what is making one  to work and the other not .

**Comment by rpitera** [comment]
I'm on a Virtualbox VM.  When I updated, the first run started spitting out some wacky stuff in the logs and I couldn't get a WebUI to open. (Sorry I don't have the logs anymore as they were overwritten, but I saw a lot of mentions of github of all things.  WTH?) 

I stopped the add on completely, waited and then started it again.  On the second run, everything seemed to start up normally again and then it was working fine after that.  Went and checked my users list and everything is still there.
