### ISSUE TITLE
Update to InfluxDB 2

### ISSUE THREAD

**Issue by mazzy89** [hassio-addons/addon-influxdb#192]
# Problem/Motivation

Upgrading InfluxDB to 2

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

InfluxDB is a major release that bring a lot of features. Is on the horizon an upgrade? Are there any known blockers?

**Comment by frenck** [comment]
See many other issues and discussions. Additionally, this is not an issue, but a feature request.

**Comment by mazzy89** [comment]
@frenck Please can you link old discussions here? Also is this the place where to make feature requests? Home Assistant Community Add-ons Discord chat server thank you

**Comment by mazzy89** [comment]
I've found it https://github.com/hassio-addons/addon-influxdb/discussions/113 baam thanks
