### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by RealFantasy** [hassio-addons/addon-influxdb#20]
# Problem

> Hi, I'm not able to pass the authentication on the browser, it keeps asking for an username and a password (I've tried with the credentials I use to login to HA).
I've also tried adding `"leave_front_door_open": true` to the config but it keeps asking for an username and a password.

## Expected behavior

> Being able to login using HA username and password

## Actual behavior

> Keeps asking for username and password

## Steps to reproduce

> Start the add-on, open `hassio_IP:8888`, log in.

**Comment by frenck** [comment]
Please share the start of the addon logs

**Comment by RealFantasy** [comment]
> Please share the start of the addon logs

Here are the logs:
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
parse error: Invalid numeric literal at line 1, column 7
ERROR: Unknown HTTP error occured
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
parse error: Invalid numeric literal at line 1, column 7
ERROR: Unknown HTTP error occured
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 20-system-users.sh: executing... 
[cont-init.d] 20-system-users.sh: exited 0.
[cont-init.d] 21-auth.sh: executing... 
[cont-init.d] 21-auth.sh: exited 0.
[cont-init.d] 30-kapacitor.sh: executing... 
[cont-init.d] 30-kapacitor.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO: Starting the InfluxDB
INFO: Chronograf is waiting until InfluxDB is available...
INFO: Kapacitor is waiting until InfluxDB is available...
INFO: Starting the Kapacitor
INFO: Starting Chronograf

'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::

2019/02/06 19:52:52 Using configuration at: /etc/kapacitor/kapacitor.conf
time="2019-02-06T19:52:53+01:00" level=info msg="Serving chronograf at http://127.0.0.1:8889" component=server 
time="2019-02-06T19:52:53+01:00" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime" ```

**Comment by bratanon** [comment]
Same issue here.

**Comment by frenck** [comment]
@bratanon Same question, please share the logs (and please include the start part as well, since it contains all version information I need in order to try to reproduce in a similar environment).

**Comment by jagibson** [comment]
I'm getting the same thing (using docker).  I think it may be a nameserver/DNS issue.  I've installed the plugin via the hass.io add-ons page.  DNS works for homeassistant which is using 172.30.32.2 but influxdb is using 127.0.0.11.  If I change the nameserver for the influxdb container to "172.30.32.2" in /etc/resolv.conf I can do an apt update, which I couldn't before.

Unfortunately when I restart the container I lose the setting in /etc/resolv.conf.  Will update if I figure anything else out.

**Comment by HetorusNL** [comment]
i'm having the same problem
(btw, the username and password i use to successfully login are the HA username and password)

**Comment by zwulk** [comment]
Same here. 
Hass.io Version: 0.76.0
My logs look like: 
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: InfluxDB v1.3.0
 Scalable datastore for metrics, events, and real-time analytics
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / HassOS 2.10 / HA 0.76.0 / SU 145 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 20-system-users.sh: executing... 
[cont-init.d] 20-system-users.sh: exited 0.
[cont-init.d] 21-auth.sh: executing... 
[cont-init.d] 21-auth.sh: exited 0.
[cont-init.d] 30-kapacitor.sh: executing... 
[cont-init.d] 30-kapacitor.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO: Kapacitor is waiting until InfluxDB is available...
INFO: Starting the InfluxDB
INFO: Chronograf is waiting until InfluxDB is available...
INFO: Starting the Kapacitor
INFO: Starting Chronograf
'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
2019/02/25 19:03:38 Using configuration at: /etc/kapacitor/kapacitor.conf
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
time="2019-02-25T19:03:39Z" level=info msg="Serving chronograf at http://127.0.0.1:8889" component=server 
time="2019-02-25T19:03:39Z" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime" `

**Comment by ultimatevn** [comment]
Seem like this addon is dead, i have same problem...

**Comment by jagibson** [comment]
Update - I installed this on my laptop just to test in a different docker environment and it all worked as expected.  I suspect there is a firewall rule on my home server that is interfering.

**Comment by fpovoski** [comment]
Same problem.  Was able to login initially but every combination of configuration login fails.

**Comment by frenck** [comment]
@ultimatevn The community add-ons are far from dead 😉 

Is any of you using the trusted_networks auth provider? If so, that is the problem. This auth provider will be removed per Home Assistant 0.95 as well. Suggestion in that case is the enable the `homeassistant` authentication provider as well.

**Comment by frenck** [comment]
No response from any of the participants, closing issue.
