### ISSUE TITLE
Move the DB to a USB Key

### ISSUE THREAD

**Issue by stphndrnd** [hassio-addons/addon-influxdb#21]
# Problem/Motivation

Not really an issue. More a feature request.

The DB will grow over time and storage on the SD card of a raspberry pi might not be enough. Plus SD cards tends to be corrupted over time with too much read/write operations. If the card gets corrupted and a re-install is done using a backup all data are gone.

## Expected behavior

All data are stored on a USB disk.

## Actual behavior

Data are stored on the SD card of the Raspberry Pi

## Proposed changes

Introduce a config option for storage path. Such as
storage_path: /dev/ttyUSB0

OR

storage_path: /dev/sda1

**Comment by frenck** [comment]
This is not supported by Hass.io, therefore I'm unable to fulfill this request.
Please file an RFC or Feature request with Hass.io.

Closing this ticket for now, since there is nothing left to do for me.
