### ISSUE TITLE
SIGILL on 2.0 startup

### ISSUE THREAD

**Issue by jeffehobbs** [hassio-addons/addon-influxdb#23]
After upgrading to 2.0, InfluxDB refuses to start in Hassio, with this error in the logs over and over until the add-on is stopped:

`[17:04:12] INFO: Starting the InfluxDB...
SIGILL: illegal instruction
PC=0x963ef0 m=0 sigcode=1
goroutine 1 [running, locked to thread]:
main.init()
	<autogenerated>:1 fp=0x4000058790 sp=0x4000058790 pc=0x963ef0
runtime.main()
	/usr/local/go/src/runtime/proc.go:189 +0x1b0 fp=0x40000587d0 sp=0x4000058790 pc=0x3ab80
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1114 +0x4 fp=0x40000587d0 sp=0x40000587d0 pc=0x65a34
r0      0x963ef0
r1      0x0
r2      0x400000
r3      0x4000098000
r4      0x0
r5      0x0
r6      0x1
r7      0x1
r8      0x4000098000
r9      0x1
r10     0x1000
r11     0x1
r12     0xd9848c
r13     0x0
r14     0xff
r15     0x0
r16     0x0
r17     0x7f9fbafb02
r18     0x0
r19     0x8
r20     0x7ff1a66f20
r21     0x1798ea0
r22     0x0
r23     0x0
r24     0x0
r25     0x0
r26     0xc877c0
r27     0xc877c0
r28     0x4000000180
r29     0x0
lr      0x3ab80
sp      0x4000058790
pc      0x963ef0
fault   0x0`

**Comment by frenck** [comment]
@jeffehobbs I'm sorry, I have a wide collection of different devices to run Hass.io on, but cannot reproduce this.

Could you share with me the log messages that are shown on the start of the add-on? That allows me to set up a similar setting (given I have access to it).

**Comment by jeffehobbs** [comment]
Sure. I see this:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 2.0.0
 You are running the latest version of this add-on.
 System: HassOS 1.13  (aarch64 / raspberrypi3-64)
 Home Assistant version: 0.90.2
 Supervisor version: 150
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in e.g, GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-nginx.sh: executing... 
[cont-init.d] 11-nginx.sh: exited 0.
[cont-init.d] 20-system-users.sh: executing... 
[cont-init.d] 20-system-users.sh: exited 0.
[cont-init.d] 21-auth.sh: executing... 
[cont-init.d] 21-auth.sh: exited 0.
[cont-init.d] 22-reporting.sh: executing... 
[cont-init.d] 22-reporting.sh: exited 0.
[cont-init.d] 30-kapacitor.sh: executing... 
[cont-init.d] 30-kapacitor.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:48:57] INFO: Starting the InfluxDB...
[18:48:57] INFO: Kapacitor is waiting until InfluxDB is available...
SIGILL: illegal instruction
PC=0x963ef0 m=0 sigcode=1
goroutine 1 [running, locked to thread]:
main.init()`

**Comment by jeffehobbs** [comment]
I took off and nuked it from space. It was the only way to be sure. :)
