### ISSUE TITLE
InfluxDB error in log on startup, InfluxDB not ready on time

### ISSUE THREAD

**Issue by bjschuit** [hassio-addons/addon-influxdb#231]
# Problem/Motivation
HA gives the following error:
Logger: homeassistant.components.influxdb
Source: components/influxdb/__init__.py:568
Integration: InfluxDB (documentation, issues)
First occurred: 16:36:20 (1 occurrences)
Last logged: 16:36:20

Could not write '[{'measurement': 'kWh', 'tags': {'domain': 'sensor', 'entity_id': 'energy_current_hour_2'}, 'time': datetime.datetime(2021, 12, 23, 15, 36, 20, 125268, tzinfo=datetime.timezone.utc), 'fields': {'value': 0.0, 'device_class_str': 'energy', 'friendly_name_str': 'Estimated Energy Production - This Hour'}}, {'measurement': 'kWh' [... and this goes on and on for many more measurements ...]

In the InfluxDB log, the last line where it mentions it is started is 2 seconds later, so at 16:36:22

My InfluxDB database is a bit big with data of 1 year of all my measurements, but for the rest it performs marvelous. 

## Proposed changes

HA should try to write the first time just a couple of seconds later, thereby preventing the issue (I assume).

**Comment by frenck** [comment]
That is an error from Home Assistant; not this add-on, you are in the wrong place.
