### ISSUE TITLE
Unable to see in add-on store?

### ISSUE THREAD

**Issue by cfgroenewald** [hassio-addons/addon-influxdb#236]
# Problem/Motivation

> I would like to install but unable to find the add-on. 

## Expected behavior

> Able to find in add on store

## Actual behavior

> (What actually happened)

## Steps to reproduce

> Please explain what I need to do to see this in the add-on store. 

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The community add-ons is installed by default, unless removed manually.

You can add it back manually by adding `https://github.com/hassio-addons/repository`

or click this My Home Assistant button alternatively:

[![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2Fhassio-addons%2Frepository)
