### ISSUE TITLE
High CPU usage of influxDB on Hassos

### ISSUE THREAD

**Issue by ralong777** [hassio-addons/addon-influxdb#237]
# Problem/Motivation

i installed new version of influxdb on 06/02/2022 and it immediatly started to draw about 50% of cpu power. and now after 2 weeks is draws 70% of my cpu (raspberry pi4) This is unacceptable pls fix.  

## Expected behavior

 much lower cpu usage

## Actual behavior

>70% cpu usage all the time

## Steps to reproduce

idk

## Proposed changes

fix it.

influx db page:
![image](https://user-images.githubusercontent.com/90091522/155229412-a8d528b6-fa09-4ce3-853f-d8b7a6d35b63.png)

last 3 month cpu usage:
![image](https://user-images.githubusercontent.com/90091522/155229951-734b8516-6c66-4d0e-89b9-ed93dc27062b.png)

**Comment by ralong777** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 4.3.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.2.7
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------

**Comment by sinclairpaul** [comment]
So when you restore the addon to the previous version the cpu usage drops?

Your posted graph doesn't correlate, I would look at how much data you are storing in Influx.

As a side note ```Raspbian GNU/Linux 10 (buster) (armv7 / raspberrypi4)``` isn't a supported system for Home Assistant.

**Comment by ralong777** [comment]
i dont know how to restore to the previous version.

How it doesn't corelate? check the first picture, is this normal?

So fuck me?
