### ISSUE TITLE
max-values-per-tag limit

### ISSUE THREAD

**Issue by JAKAMI99** [hassio-addons/addon-influxdb#239]
# Problem/Motivation

> (I was wondering how I can change the "max-values-per-tag parameter)

##Issue

> One of my data "feeder" logged:
 "Error: 400: {"error":"partial write: max-values-per-tag limit exceeded (100000/100000): measurement=\"nginx_access_logs\" tag=\"datetime\" value=\"2022-03-01 02:42:39+01:00\" dropped=1"}
GEOIP2INFLUX 01/Mar/2022 02:42:40 :: ERROR :: Error writing data to InfluxDB! Check your database!")

##Solution
A way do edit the configuration of influxdb, to change the parameter which is limiting and is leading to this error

**Comment by sinclairpaul** [comment]
You can't with the addon, in all honesty if you are pushing that much data you may want to host the application separately.
