### ISSUE TITLE
Way to add lines to influxdb.conf

### ISSUE THREAD

**Issue by MoHf7f4** [hassio-addons/addon-influxdb#24]
# Problem/Motivation

Influx can take more services input directly than is configured by the current plugin.

## Expected behavior

Add a way to add text blocks to influxdb.conf

## Actual behavior

No persistent way to add additional config lines to influxdb.conf

## Proposed changes

If there was a way to put a list style object or append a file to the config it would be ideal.

example of the lines needed:
[[graphite]]
  enabled = true
  bind-address = ":2003"
  protocol = "tcp"
  # consistency-level = "one"

[[graphite]]
  enabled = true
  bind-address = ":2004" # the bind address
  protocol = "udp" # protocol to read via
  udp-read-buffer = 8388608 # (8*1024*1024) UDP read buffer size

**Comment by frenck** [comment]
I'm not planning on building / adding those features, especially with InfluxDB 2.0 around the corner.
Secondly, this sounds more like a job for Telegraf.
