### ISSUE TITLE
Is it a time to upgrade to InfluxDB OSS 2 ?

### ISSUE THREAD

**Issue by to-masz** [hassio-addons/addon-influxdb#244]
# Problem/Motivation

> InfluxDB 1.8 will continue to be maintained and receive defect fixes through the end of 2021. But InfluxDB 1.8 (and subsequent maintenance releases) will be the last official release on the 1.x line that will be built and distributed by InfluxData.

Home Assistant integration supports both versions of InfluxDB (https://www.home-assistant.io/integrations/influxdb/).

InfluxDB is quite popular add-on with [9581 installs (12.9 %)](https://analytics.home-assistant.io/#add-ons). 

Most of the people do not read change logs, so introducing breaking changes here would be a big pain for HA users.

You do not accept 3rd party add-ons to the official repository ("We are currently not accepting third party add-ons to this repository.").

Many people keep Home Assistant ecosystem closed from public Internet and don't want to use InfluxDB Cloud (even its free version is an interesting option). 

## Proposed changes

@frenck would you be willing to add `addon-influxdb2`? are you open for the contribution?

**Comment by frenck** [comment]
Multiple topics on the matter can be found, no need to open a new issue for it.
Additionally, this is not directly related to the add-on and no, I do not accept third-party add-ons to the repository at this moment (as documented, which you have pointed out).

**Comment by to-masz** [comment]
Ok, so it looks like "multiple topics" is just an official add-on thread here: https://community.home-assistant.io/t/home-assistant-community-add-on-influxdb/54491/330 where Guilhem announced to start a work on the add-on, but after few weeks there are no results as he hasn't have much time.

I think about only three options for now:
1. Reconsider [Long-Term Statistics](https://data.home-assistant.io/docs/statistics). 
2. Reconsider InfluxDB cloud.  
3. Maintain the new add-on on our own

**Comment by frenck** [comment]
🤷
