### ISSUE TITLE
Add data from external source into Hassio influxdb

### ISSUE THREAD

**Issue by snaven1** [hassio-addons/addon-influxdb#246]
# Problem/Motivation
Data externally outside of the hassio environment cannot be brought into a supervised docker based Hassio Influxdb instance. 
> (Why the issue was filed)

## Expected behavior
Should work
> (What you expected to happen)

## Actual behavior
Doen't work
> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
My local home environment is running on a 192.168.100.0/24 network, with hassio running on a private docker based network where all hassio components run on separate docker containers in the 172.20.32.0/23 range. The host to the docker system is in 192... range. The issue is moving data into the influxdb docker container via a telegraf write. Have attempted writing to the exposed 8086 port without success, and have also tried writing via Nginx reverse proxy without success. The typical error from telegraf log

[outputs.influxdb] When writing to [http://hassist:80 OR 8086/a0d7b954_influxdb]: failed doing req: Post "http://hassist:80 OR 8086/a0d7b954-influxdb/write?db=HBase_Tank1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

I have tried many variations of both these techniques without success.
Nothing shows up in either the Nginx log nor the Influxdb log. I know this works as currently I have this happening outside of the hassio environment. It should be noted that the addon for InfluxDB is currently receiving data internally from Home Assistant without issue. Thanks for any assistance.

**Comment by frenck** [comment]
Closing as the above response from Paul is correct.
