### ISSUE TITLE
Cannot add new Influx Users to 3.0.0

### ISSUE THREAD

**Issue by jeffehobbs** [hassio-addons/addon-influxdb#25]
# Problem/Motivation

After a clean install of InfluxDB-addon 3.0.0 on RPi 3B+/32bit, with the default add-on settings, I cannot add a user with permissions. 

## Expected behavior

A new user should be created and I should be able to assign permissions to that user.

## Actual behavior

Permissions cannot be granted to the new user (listing permissions as "None") and attempts to add permissions to user results in error: "Failed to update User Permissions: undefined".

## Steps to reproduce

Install 3.0.0, follow instructions from here: https://github.com/hassio-addons/addon-influxdb#integrating-into-home-assistant

## Proposed changes

Users should be able to be created (or mirrored from Home Assistant?) and db permissions should be able to be assigned.

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-influxdb">hassio-addons/addon-influxdb</a></strong></div><div>InfluxDB - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-influxdb</div></blockquote>

**Comment by frenck** [comment]
The issue has been located and will be fixed soon. Sorry for the inconvenience

**Comment by jeffehobbs** [comment]
👍 !
