### ISSUE TITLE
InfluxDB 4.5.0 pegs CPU at 62% constantly and will not startup properly

### ISSUE THREAD

**Issue by Johnny140** [hassio-addons/addon-influxdb#258]
# Problem/Motivation
I am running HA in a VM on Proxmox and have been doing so for about 5 years. VM has 2GB of RAM, 1 socket/2 cores with RAM usage below 1GB.  HA - 2022.11, supervisor 2022.10.2, os 9.3, frontend 20221102.1 (Proxmox running on an AMD Ryzen 9 5950X with 64GB of RAM)
InfluxDB addon not working properly.
Restarting the addon did not help
console from HA had many lines: <time stamp> Out of memory: Killed process <process #> (influxdb) total-vm:<numberkB>, anon-rss:<numberkB>, file-rss:0kB, shem-rss:0kB, UID:0 pgtables:<numberkB> oom-score_adj:200.
Process # 174XXXX, 175XXXX
total-vm: 107XXXXkB or higher
anon-rss:22XXXXkB

Rebooted HA, same issue. Rebooted again and it settled down, but I lost all my settings
[HA console - influxdb issue.pdf](https://github.com/hassio-addons/addon-influxdb/files/9961866/HA.console.-.influxdb.issue.pdf)
[InfluxDB - log.txt](https://github.com/hassio-addons/addon-influxdb/files/9961898/InfluxDB.-.log.txt)

> (Why the issue was filed)
To report an issue with the add-on

## Expected behavior
to run properly

> (What you expected to happen)
To work

## Actual behavior
Does not run as it should, endless stop, restarting

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
[InfluxDB - log.txt](https://github.com/hassio-addons/addon-influxdb/files/9961913/InfluxDB.-.log.txt)
[HA console - influxdb issue.pdf](https://github.com/hassio-addons/addon-influxdb/files/9961917/HA.console.-.influxdb.issue.pdf)

**Comment by CarlosGS** [comment]
It could be related to a memory leak & general slowness in the recent versions of HASS:
- https://github.com/home-assistant/core/issues/81691
- https://github.com/home-assistant/core/issues/82309
- https://github.com/home-assistant/core/issues/81756

Can you check RAM usage history since then?

**Comment by MasterCATZ** [comment]
pretty sure it is this HAOS memory leak issue 
I moved my influxDB to an external instance and removed all the HAOS mariadb and influxdb docker containers 
it is still using more RAM than it used too but at least the OOM ended 
also using my external instances seem to be using less RAM than the docker containers
