### ISSUE TITLE
"This update is no longer compatible with your system." with 3.0.2

### ISSUE THREAD

**Issue by SiliconAvatar** [hassio-addons/addon-influxdb#26]
# Problem/Motivation

Currently running 3.0.0, when I checked the new version that's avilable, it simply says:
`This update is no longer compatible with your system.`

My system is Ubuntu linux, running on a NUC-

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.2
timezone | America/New_York
version | 0.91.3
virtualenv | false

I suspect this is an error somewhere?

**Comment by frenck** [comment]
Update to Home Assistant 0.91.4, as per release notes.

**Comment by SiliconAvatar** [comment]
Fixed by updating HA to 0.91.4; perhaps this should be in the changelog or somewhere else to make this clear.

**Comment by frenck** [comment]
it is in the changelog.
