### ISSUE TITLE
Feature request: Export udp port for collected

### ISSUE THREAD

**Issue by manuel-arguelles** [hassio-addons/addon-influxdb#266]
Hi,

I know this feature has been proposed before and rejected, however, the implementation should be easy, as far as I understand it is only a matter of exporting an udp port in the container. (the rest can be handled with the environment variables)

```
--- a/influxdb/config.yaml
+++ b/influxdb/config.yaml
@@ -24,9 +24,11 @@ map:
 ports:
   80/tcp: null
   8086/tcp: 8086
+  25826/udp: 25826
 ports_description:
   80/tcp: Web interface (Not required for Ingress)
   8086/tcp: InfluxDB server
+  25826/udp: Collectd port
 auth_api: true
 options:
   auth: true
```

In order to test it, i copied the repository into my local addons directory but it fails to install with:

```
The command '/bin/bash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends libnginx-mod-http-lua=1.18.0-6.1 luarocks=2.4.2+dfsg-1.1 nginx=1.18.0-6.1 procps=2:3.3.17-5 && luarocks install lua-resty-http 0.15-0 && ARCH="${BUILD_ARCH}" && if [ "${BUILD_ARCH}" = "aarch64" ]; then ARCH="arm64"; fi && if [ "${BUILD_ARCH}" = "armv7" ]; then ARCH="armhf"; fi && INFLUXDB="1.8.10" && curl -J -L -o /tmp/influxdb.deb "https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUXDB}_${ARCH}.deb" && CHRONOGRAF="1.9.4" && curl -J -L -o /tmp/chronograf.deb "https://dl.influxdata.com/chronograf/releases/chronograf_${CHRONOGRAF}_${ARCH}.deb" && KAPACITOR="1.5.9-1" && curl -J -L -o /tmp/kapacitor.deb "https://dl.influxdata.com/kapacitor/releases/kapacitor_${KAPACITOR}_${ARCH}.deb" && dpkg --install /tmp/influxdb.deb && dpkg --install /tmp/chronograf.deb && dpkg --install /tmp/kapacitor.deb && rm -fr /tmp/* /etc/nginx /var/{cache,log}/* /var/lib/apt/lists/* && mkdir -p /var/log/nginx && touch /var/log/nginx/error.log' returned a non-zero code: 100
```

I have zero experience with addons, but if you could point me in the right direction to at least test this locally, I'd appreciated it.

Thanks!

**Comment by sinclairpaul** [comment]
As it is UDP it would also need to be on the host network

**Comment by manuel-arguelles** [comment]
I didn't know that UDP has different requirements, just noticed that port 8086 is available from the host and thought that adding a new one would just be a matter of adding it to the config file.

I need to dig more into it, at the moment I just cloned the repository into my local addons directory and tried to install it, probably not the correct way.

**Comment by frenck** [comment]
This feature has been requested for a couple of times before, and declined.

Please use the search before opening issues.

Going to close this issue, as it is a feature request.

../Frenck
