### ISSUE TITLE
Quickly upgrade InfluxDB to 1.7.6 due to critical issue

### ISSUE THREAD

**Issue by tburchhardt** [hassio-addons/addon-influxdb#27]
# Problem/Motivation

InfluxDB 1.7.5 includes a critical issue which can bring all queries  & writes to the homassistant DB to a stop, this is hitting my system since yesterday and should be fixed with InfluxDB 1.7.6

https://www.influxdata.com/blog/release-announcement-influxdb-1-7-6-and-chronograf-1-7-10/

> Addressed a critical defect with 1.7.5 which for those using the inmem index where InfluxDB would become unresponsive and no longer accept writes or query requests.

**Comment by frenck** [comment]
Done, add-on v3.0.3 is now available.
