### ISSUE TITLE
UDP

### ISSUE THREAD

**Issue by fl4p** [hassio-addons/addon-influxdb#270]
I see users  asked this a  couple of times. Why did the maintainer decline?
Writing points with UDP makes a lot of sense, especially for IoT.
The [tutorial](https://www.influxdata.com/blog/how-to-send-sensor-data-to-influxdb-from-an-arduino-uno/) by InfluxDB on how to write data from an Arduino is about UDP only.  
UDP may be forgotten because internet lobbyist didn't like it (no congestion control). Its simplicity make it very attractive for simple messaging in local networks. InfluxDB UDP API will not disappear.

**Comment by ssditt** [comment]
Yes, line protocol via UDP will be great!

**Comment by fl4p** [comment]
It would just need to set `host_network: true` in config.yaml.
I could not find a way to override this value in HA, need to patch this add-on with the modified config.yaml.

**Comment by fl4p** [comment]
I created a simple add-on that forwards UDP writes to the HTTP API
https://github.com/fl4p/influxdb-udp-relay

**Comment by frenck** [comment]
> I see users asked this a couple of times. Why did the maintainer decline?

Please see the history of the issue, the same issue you looked at to see it was already asked a couple of times.

../Frenck

**Comment by fl4p** [comment]
I looked into all these issues. You never told a reason.
Will you ever tell us?

**Comment by frenck** [comment]
I did tell a reason a couple of times. I'm just stopped repeating it, as I don't feel like it anymore. I will not be added.

../Frenck
