### ISSUE TITLE
InfluxDB database is not accessible due to 401

### ISSUE THREAD

**Issue by Skysurfer-14** [hassio-addons/addon-influxdb#278]
I've installed the addon today and can not get it to run. 

I have created my own database "homeAssistant" in InfluxDB and also a user "homeAssistant" with read and write permissions to the database and have also included this data in the configuration.yaml, but I always get this error message:

```
Logger: homeassistant.components.influxdb
Source: components/influxdb/__init__.py:490
Integration: InfluxDB (documentation, issues)
First occurred: 18:15:20 (11 occurrences)
Last logged: 18:25:21

InfluxDB database is not accessible due to '401: {"error":"authorization failed"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.
```

**Comment by frenck** [comment]
This is not an add-on error; you are raising an issue about an Home Assistant integration issue. This is not a issue tracker for the Home ASsistant integration.

../Frenck
