### ISSUE TITLE
zero values are not being send to InfluxDB

### ISSUE THREAD

**Issue by MarpleA** [hassio-addons/addon-influxdb#283]
# Problem/Motivation

I use power plugs to measure my power consumption. If these plugs are switched off and the corresponding entity shows the value 0 in HA, this number is not being send to influxdb. I am not entirely sure what causes this issue or if it's maybe a wanted feature.

## Expected behavior

send value 0 to get the full graph of power consumption

## Actual behavior

> (What actually happened)

## Steps to reproduce

simply switch off any power measuring plug

**Comment by sinclairpaul** [comment]
This isn't an issue with the addon but how the integration functions, would suggest reaching out on the HA forums or discord.
