### ISSUE TITLE
Chronograf crashes when a colon is entered

### ISSUE THREAD

**Issue by Aston77** [hassio-addons/addon-influxdb#285]
# Problem/Motivation

Attempting to create a continuous query and Chronograf crashes as soon as I enter the colon in front of "Measurement"

## Expected behavior

Query executes properly

## Actual behavior

InfluxQL tab - Chronograf crashes when the colon is entered
Flux tab - error " loc 3:15-3:16: unexpected token for property key: MUL ("*")

## Steps to reproduce

Enter the below query
```
CREATE CONTINUOUS QUERY "cq_downsample_1m" ON "homeassistant"

BEGIN

SELECT mean(*) INTO "homeassistant"."1m".:MEASUREMENT FROM "homeassistant"."autogen"./.*/

GROUP BY time(1m), *

FILL(previous)

END
```

Log file from Edge browser (Version 113.0.1774.42) Dev console
[homeassistant.local-1684287519742.log](https://github.com/hassio-addons/addon-influxdb/files/11493369/homeassistant.local-1684287519742.log)

![msedge_5YAF2KjNZ8](https://github.com/hassio-addons/addon-influxdb/assets/78501124/b2a92258-d0b4-48af-b168-89eee111b08d)

![image](https://github.com/hassio-addons/addon-influxdb/assets/78501124/ce6c9045-0818-431e-b636-08979d6d5138)

**Comment by sinclairpaul** [comment]
So from initial investigation it would appear this is an upstream issue, there are multiple reports at https://github.com/influxdata/chronograf/issues with different O/S and platform combinations.

I doubt there is anything we can do here.
