### ISSUE TITLE
Failed to start add-on

### ISSUE THREAD

**Issue by Roselt** [hassio-addons/addon-influxdb#289]
InfluxDB add-on version 4.7.0

The add-on stopped working somewhere in the past week. 
When I try to start the add-on, I get the following error:
500 Server Error for http+docker://localhost/v1.42/containers/addon_a0d7b954_influxdb/json: Internal Server Error ("stat /mnt/data/docker/overlay2/5a2293c14b6a0cde4eaa1edeb1def23fd4162fb23a26723a792fb9ddb832ac3f: no such file or directory")

I have tried restoring a backup, I also tried uninstalling and re-installing the add-on but still get the same error.

**Comment by frenck** [comment]
> 500 Server Error for http+docker://localhost/v1.42/containers/addon_a0d7b954_influxdb/json: Internal Server Error ("stat /mnt/data/docker/overlay2/5a2293c14b6a0cde4eaa1edeb1def23fd4162fb23a26723a792fb9ddb832ac3f: no such file or directory")

This is an issue on your system and not something the add-on can do anything about.

Try running `ha supervisor repair` from a terminal and see if HA can fix your corruption there. If the issue remains, I would suggest raising an issue with the Home Assistant Supervisor project.

Wish I had a better answer for you.

../Frenck
