### ISSUE TITLE
flooding the network with uneeded packets

### ISSUE THREAD

**Issue by gnkarn** [hassio-addons/addon-influxdb#29]
# Problem/Motivation
today i  was chasing an unusual network behaviour , by looking at pihole dahsboar i saw that influxdb addon generated 1.200.000  hits in the last 24 hours .
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
i think that the config parameter "reporting"  should be set to false by default .

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I'm not setting it to false by default, since that is not the default of InfluxDB.

Feel free to set it to false if you don't like it.

Thanks for your suggestion.
