### ISSUE TITLE
Running influxd in the SSH & Terminal add-on gives a command not found error

### ISSUE THREAD

**Issue by Gio-dot** [hassio-addons/addon-influxdb#293]
# Problem/Motivation

Im looking for a way to backup influxdb database using Terminal & SSH addon

## Expected behavior

Working influxdb backup command

## Actual behavior

influxd: command not found
![image](https://github.com/hassio-addons/addon-influxdb/assets/55327160/7f8307b4-685e-4ba7-9e87-bbd1a2b023ee)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Can you please explain me in detail (sorry, i'm quite new in Terminal use) a workaround if exist?

**Comment by jorgedso** [comment]
Are you executing that command inside InfluxDB container?

**Comment by jmsblah** [comment]
> Are you executing that command inside InfluxDB container?

how do i get into the docker container to run the command?

**Comment by jorgedso** [comment]
> > Are you executing that command inside InfluxDB container?
> 
> how do i get into the docker container to run the command?

You do it using something like this sudo docker exec -ti <container_id> bash
