### ISSUE TITLE
InfluxDB 4.7.0 does not start

### ISSUE THREAD

**Issue by jorgedso** [hassio-addons/addon-influxdb#295]
# Problem/Motivation

> After upgrading InfluxDB add-on from 4.6.0 to 4.7.0 it was not able to start.

## Expected behavior

> After upgrade it should keep starting normally as before.

## Actual behavior

> Even after uninstalling, restarting HA totally, and installing again, it does not start

`s6-rc: info: service base-addon-banner successfully started`
`s6-rc: info: service fix-attrs: starting`
`s6-rc: info: service base-addon-timezone: starting`
`s6-rc: info: service base-addon-log-level: starting`
`s6-rc: info: service fix-attrs successfully started`
`[23:33:12] INFO: Configuring timezone (Europe/Lisbon)...`
`s6-rc: info: service base-addon-log-level successfully started`
`s6-rc: info: service base-addon-timezone successfully started`
`s6-rc: info: service legacy-cont-init: starting`
`cont-init: info: running /etc/cont-init.d/create-users.sh`
`/etc/cont-init.d/create-users.sh: line 16: influxd: command not found`
`[23:33:16] INFO: InfluxDB init process in progress...`
`[23:33:21] INFO: InfluxDB init process in progress...`
`[23:33:26] INFO: InfluxDB init process in progress...`
`[23:33:31] INFO: InfluxDB init process in progress...`
`[23:33:36] INFO: InfluxDB init process in progress...`
`...`
`[02:03:37] INFO: InfluxDB init process in progress...`
`[02:03:42] INFO: InfluxDB init process in progress...`
`[02:03:47] INFO: InfluxDB init process in progress...`
`[02:03:52] INFO: InfluxDB init process in progress...`
`[02:03:57] INFO: InfluxDB init process in progress...`
`[02:04:02] INFO: InfluxDB init process in progress...`
`[02:04:07] FATAL: InfluxDB init process failed.`
`cont-init: info: /etc/cont-init.d/create-users.sh exited 1`
`cont-init: info: running /etc/cont-init.d/influxdb.sh`
`cont-init: info: /etc/cont-init.d/influxdb.sh exited 0`
`cont-init: info: running /etc/cont-init.d/kapacitor.sh`
`/etc/cont-init.d/kapacitor.sh: line 8: /data/secret: No such file or directory`
`cont-init: info: /etc/cont-init.d/kapacitor.sh exited 0`
`cont-init: info: running /etc/cont-init.d/nginx.sh`
`cont-init: info: /etc/cont-init.d/nginx.sh exited 0`
`cont-init: warning: some scripts exited nonzero`
`s6-rc: warning: unable to start service legacy-cont-init: command exited 1`
`/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.`
`/run/s6/basedir/scripts/rc.init: fatal: stopping the container.`
`s6-rc: info: service fix-attrs: stopping`
`s6-rc: info: service base-addon-timezone: stopping`
`s6-rc: info: service base-addon-log-level: stopping`
`s6-rc: info: service fix-attrs successfully stopped`
`s6-rc: info: service base-addon-timezone successfully stopped`
`s6-rc: info: service base-addon-log-level successfully stopped`
`s6-rc: info: service base-addon-banner: stopping`
`s6-rc: info: service base-addon-banner successfully stopped`
`s6-rc: info: service s6rc-oneshot-runner: stopping`
`s6-rc: info: service s6rc-oneshot-runner successfully stopped`

## Steps to reproduce

> Just start add-on

**Comment by chsims1** [comment]
I'm seeing similar behaviour (not starting) after rolling back to an earlier full backup of HA. 

InfluxDB log:

`2023/07/21 11:48:02 Using configuration at: /etc/kapacitor/kapacitor.conf
time="2023-07-21T11:48:15+01:00" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime"
time="2023-07-21T11:48:15+01:00" level=info msg="Serving chronograf at http://127.0.0.1:8889" component=server
[11:48:15] INFO: Starting NGINX...`

Supervisor log:

`23-07-21 11:58:58 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
23-07-21 11:58:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
23-07-21 11:58:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
23-07-21 12:00:34 WARNING (MainThread) [supervisor.addons.addon] a0d7b954_influxdb is already running!
23-07-21 12:02:34 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon InfluxDB to start, took more then 120 seconds
`
