### ISSUE TITLE
influxdbv2

### ISSUE THREAD

**Issue by dudu7731** [hassio-addons/addon-influxdb#297]
# Problem/Motivation
I'm looking for influxdb V2 on addons and it's missing

## Expected behavior
influxdb V2 is available

## Actual behavior
only V1 can be installed

## Steps to reproduce
look for influxdb in addons store

## Proposed changes
make V2 installable

**Comment by mitch55500** [comment]
Hi, 

Or, maybe, can you explain how to upgrade to influx2.*

I'd like to try [this](https://docs.influxdata.com/influxdb/v2/upgrade/v1-to-v2/docker/), but I don't know how to adapt it...

**Comment by dMopp** [comment]
There is a 3rd Party addon for influxdb2, see https://community.home-assistant.io/t/home-assistant-add-on-influxdb-v2/617977

**Comment by mitch55500** [comment]
Oh, great ! I didn't know ; yet, I've have searched.
Thanks.
