### ISSUE TITLE
After moving to 3.0.4 I can no longer launch the Web UI

### ISSUE THREAD

**Issue by cdrom1028** [hassio-addons/addon-influxdb#30]
# Problem/Motivation

I can not access the Web UI

## Expected behavior

the web ui would open and I could configure data sources

## Actual behavior

When I click on the web ui link in the addon screen or the side panel link in Home assistant and the frame goes dark but the interface never renders

## Steps to reproduce

click on the web ui link in the addon screen or the side panel link in Home assistant 

from Hassio logs:
```
19-04-29 12:49:53 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on hassioaddons/influxdb-amd64 with version v3.0.4
19-04-29 12:49:53 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_influxdb
19-04-29 12:49:54 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.4:1337 ssl:None [Connection refused]
```

## Proposed changes

I just want to access the database Ui

**Comment by frenck** [comment]
Please check the add-on logs...
