### ISSUE TITLE
Add-on doesn't start 

### ISSUE THREAD

**Issue by benek984** [hassio-addons/addon-influxdb#300]
# Problem/Motivation

Add-on doesnt start at all

## Expected behavior

Should start

## Actual behavior

Add-on doesnt start at all

## Steps to reproduce

Start add-on

## Proposed changes
LOGS:

s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 4.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.0
 Home Assistant Supervisor: 2023.08.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[13:44:20] INFO: Configuring timezone (Europe/London)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/create-users.sh
cont-init: info: /etc/cont-init.d/create-users.sh exited 0
cont-init: info: running /etc/cont-init.d/influxdb.sh
cont-init: info: /etc/cont-init.d/influxdb.sh exited 0
cont-init: info: running /etc/cont-init.d/kapacitor.sh
cont-init: info: /etc/cont-init.d/kapacitor.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun chronograf (no readiness notification)
services-up: info: copying legacy longrun influxdb (no readiness notification)
services-up: info: copying legacy longrun kapacitor (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
[13:44:20] INFO: Kapacitor is waiting until InfluxDB is available...
[13:44:20] INFO: Chronograf is waiting until InfluxDB is available...
s6-rc: info: service legacy-services successfully started
[13:44:20] INFO: Starting the InfluxDB...
[13:44:37] INFO: Starting the Kapacitor
[13:44:37] INFO: Starting Chronograf...
'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
2023/09/12 13:44:38 Using configuration at: /etc/kapacitor/kapacitor.conf
ts=2023-09-12T13:44:42.136+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
ts=2023-09-12T13:44:42.371+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
[13:44:42] INFO: InfluxDB stopped, restarting...
ts=2023-09-12T13:44:43.119+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
[13:44:43] INFO: Starting the InfluxDB...
ts=2023-09-12T13:44:43.788+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
ts=2023-09-12T13:44:46.254+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
time="2023-09-12T13:44:47+01:00" level=info msg="Serving chronograf at http://127.0.0.1:8889" component=server
time="2023-09-12T13:44:47+01:00" level=info msg="Reporting usage stats" component=usage freq=24h reporting_addr="https://usage.influxdata.com" stats="os,arch,version,cluster_id,uptime"
[13:44:47] INFO: Starting NGINX...
ts=2023-09-12T13:44:49.448+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
ts=2023-09-12T13:44:51.487+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
ts=2023-09-12T13:44:58.396+01:00 lvl=error msg="error while sending usage report on startup" service=reporting err="Post \"https://usage.influxdata.com/api/v1/usage/kapacitor\": dial tcp 0.0.0.0:443: connect: connection refused"
[13:45:05] INFO: InfluxDB stopped, restarting...
[13:45:06] INFO: Starting the InfluxDB...
[13:45:27] INFO: InfluxDB stopped, restarting...
[13:45:28] INFO: Starting the InfluxDB...
[13:45:45] INFO: InfluxDB stopped, restarting...
[13:45:46] INFO: Starting the InfluxDB...
[13:46:02] INFO: InfluxDB stopped, restarting...
[13:46:03] INFO: Starting the InfluxDB...
[13:46:25] INFO: InfluxDB stopped, restarting...
[13:46:26] INFO: Starting the InfluxDB...
[13:46:47] INFO: InfluxDB stopped, restarting...
[13:46:48] INFO: Starting the InfluxDB...
[13:47:11] INFO: InfluxDB stopped, restarting...
[13:47:12] INFO: Starting the InfluxDB...
[13:47:34] INFO: InfluxDB stopped, restarting...
[13:47:35] INFO: Starting the InfluxDB...
ts=2023-09-12T13:47:42.107+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
ts=2023-09-12T13:47:42.377+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
ts=2023-09-12T13:47:42.983+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
ts=2023-09-12T13:47:44.073+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
ts=2023-09-12T13:47:45.178+01:00 lvl=error msg="failed to connect to InfluxDB, retrying..." service=influxdb cluster=default err="Get \"http://localhost:8086/ping\": dial tcp 127.0.0.1:8086: connect: connection refused"
[13:47:56] INFO: InfluxDB stopped, restarting...
[13:47:57] INFO: Starting the InfluxDB...
[13:48:23] INFO: InfluxDB stopped, restarting...
[13:48:24] INFO: Starting the InfluxDB...
[13:48:51] INFO: InfluxDB stopped, restarting...
[13:48:52] INFO: Starting the InfluxDB...
[13:49:14] INFO: InfluxDB stopped, restarting...
[13:49:15] INFO: Starting the InfluxDB...
[13:49:37] INFO: InfluxDB stopped, restarting...
[13:49:38] INFO: Starting the InfluxDB...

**Comment by Th3M1k3y** [comment]
I am now having the same problem, did you find a solution?

**Comment by digitalit** [comment]
I get no errors in log, just saying "INFO: Starting NGINX..." but it never starts.
