### ISSUE TITLE
 I would like to ask how to perfectly migrate the Homeassistant's Influxdb database to the 2.7 version of Influxdb. I know that different versions of backup files are different

### ISSUE THREAD

**Issue by jjcszxh** [hassio-addons/addon-influxdb#301]
I would like to ask how to perfectly migrate the Homeassistant's Influxdb database to the 2.7 version of Influxdb. I know that different versions of backup files are different

**Comment by jjcszxh** [comment]
Can you update the secondary add-on version to version 2. x

**Comment by maquowicz** [comment]
Bumping this up as 1.x is missing loads of features.
