### ISSUE TITLE
Chronograf crashes when typing a ":" in query

### ISSUE THREAD

**Issue by simbb4711** [hassio-addons/addon-influxdb#305]
# Problem/Motivation

When using the chronograph UI you can't type an ":" into the query field without crashing chronograf. This makes it unusable.

## Proposed changes

A new build should fix it because the problem was fixed with issue https://github.com/influxdata/chronograf/pull/6056.

**Comment by BanditJackpot** [comment]
Same issue here, any chance this is likely to be fixed for the addon soon?

**Comment by Horstexplorer** [comment]
Yes this issue should have been resolved with version 1.10.2
<https://github.com/influxdata/chronograf/releases/tag/v1.10.2>

**Comment by frenck** [comment]
Fixed by #312
