### ISSUE TITLE
Can infuxdb be updated to 2. x

### ISSUE THREAD

**Issue by jjcszxh** [hassio-addons/addon-influxdb#307]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This add-on provides InfluxDB 1, not 2. I cannot answer that question for you.
