### ISSUE TITLE
InfluxDB not working after updating to 4.8.0

### ISSUE THREAD

**Issue by janneho** [hassio-addons/addon-influxdb#308]
# Problem/Motivation

InfluxDB not working after update to 4.8.0.
EDIT. influxdb was working, but stopped after updating home assistant core to 2023.11.0.

## Actual behavior

Logs shows:
```Logger: root
Source: components/influxdb/__init__.py:436
First occurred: 10:24:54 (1 occurrences)
Last logged: 10:24:54

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 595, in run
    self.write_to_influxdb(json)
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 571, in write_to_influxdb
    self.influx.write(json)
  File "/usr/src/homeassistant/homeassistant/components/influxdb/__init__.py", line 436, in write_v1
    influx.write_points(json, time_precision=precision)
  File "/usr/local/lib/python3.11/site-packages/influxdb/client.py", line 603, in write_points
    return self._write_points(points=points,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb/client.py", line 681, in _write_points
    self.write(
  File "/usr/local/lib/python3.11/site-packages/influxdb/client.py", line 407, in write
    data = make_lines(data, precision).encode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb/line_protocol.py", line 201, in make_lines
    line = make_line(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/influxdb/line_protocol.py", line 164, in make_line
    for field_key in sorted(fields.keys()):
                     ^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'datetime.date' and 'str'
```

## Steps to reproduce

Update home assistant core to 2023.11.0 on hassos Raspberry Pi 4.

**Comment by EDIflyer** [comment]
I've had this too, all data stopped being logged as of 30th October.  I didn't change anything in my `configuration.yml` but am not sure how to resolve - what did you change @janneho ?

**Comment by janneho** [comment]
It is not working. I do not know what to do anymore. Old data is available, but can not get it logging new data.

I have 2 yeras of data logged in, do not want to lose that. If i remove addon, and install it again is everything gone?

**Comment by EDIflyer** [comment]
I'm in exactly the same situation - old data loads fine but no new data added for the past fortnight.

**Comment by Timandrias** [comment]
I'm having a similar issue with the 4.8.0 (though the error message that I get says that Kapacitor couldn't start). I solved it by using backups to return the core to 2023.11.1 and Influx to 4.7.0. Personally, I'm suspecting the add on installer believes I'm in a different architecture than what I'm actually at, having issues with several add ons and the errors point in that general direction (but I have very little idea about what I'm doing so use salt to taste).

`ont-init: info: running /etc/cont-init.d/influxdb.sh
cont-init: info: /etc/cont-init.d/influxdb.sh exited 0
cont-init: info: running /etc/cont-init.d/kapacitor.sh
/etc/cont-init.d/kapacitor.sh: line 12:   325 Done                    bashio::var.json reporting "^$(bashio::config 'reporting')" secret "$(< /data/secret)"
       326 Segmentation fault      (core dumped) | tempio -template /etc/kapacitor/templates/kapacitor.gtpl -out /etc/kapacitor/kapacitor.conf
cont-init: info: /etc/cont-init.d/kapacitor.sh exited 139
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping`

**Comment by Farfar7575** [comment]
I am having same issue. In my case the conflict was caused in combination with the combination of Hyundai / Kia Connect integration and Influxdb for details refer to 

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/755#issuecomment-1818900040

**Comment by janneho** [comment]
> I am having same issue. In my case the conflict was caused in combination with the combination of Hyundai / Kia Connect integration and Influxdb for details refer to
> 
> [Hyundai-Kia-Connect/kia_uvo#755 (comment)](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/755#issuecomment-1818900040)

Never would i have guessed that it is hyundai integration that is causing this to happen.

I toi have hyundai/kia integration installed...

**Comment by markruys** [comment]
@janneho : the maintainers wrote a work around for this issue: https://github.com/Hyundai-Kia-Connect/kia_uvo/commit/e62b89f86c7e34b4c532ea183887154c6c26c67a. Not yet released, but applying the change manually is easy.

**Comment by janneho** [comment]
> @janneho : the maintainers wrote a work around for this issue: [Hyundai-Kia-Connect/kia_uvo@e62b89f](https://github.com/Hyundai-Kia-Connect/kia_uvo/commit/e62b89f86c7e34b4c532ea183887154c6c26c67a). Not yet released, but applying the change manually is easy.

That works, influx works again.

**Comment by Twilek-de** [comment]
Would it be a good idea and feasable  to implement a sanity check of the incoming data, so that a rogue integration cannot wreck the whole database?
