### ISSUE TITLE
What vesion InfluxDB in the addon? Can i update to the 3 version

### ISSUE THREAD

**Issue by userosos** [hassio-addons/addon-influxdb#311]
What vesion InfluxDB in the addon? I think it 1.8 - it is very old version.
How can i uses last version InfluxDB use the addon? In the moment we have InfluxDB 3.

**Comment by frenck** [comment]
See history, this add-on provide 1.8. Not the newer versions.

**Comment by userosos** [comment]
> See history, this add-on provide 1.8. Not the newer versions.

Can i use the latest version?
https://www.influxdata.com/blog/influxdb-3-0-is-2.5x-45x-faster-compared-to-influxdb-open-source/

**Comment by frenck** [comment]
See my previous message?

**Comment by userosos** [comment]
> See my previous message?

Do you have an plans for upgrade to 3 version?
