### ISSUE TITLE
Suddenly no Home assistant backups work anymore if influx addon is selected for backup

### ISSUE THREAD

**Issue by stefanschaedeli** [hassio-addons/addon-influxdb#322]
# Problem/Motivation

Suddenly my weekly backups did not succeed anymore. after inscpection is got clear that all backups work as long the influx addon is not selected

## Expected behavior

the TAR file gets created and will be listed as a backup in the gui

## Actual behavior

the tar file gets created but is corrupted, cant be unziped and also home assistant is not listing the backup

`[32m24-02-23 21:54:30 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_influxdb[0m
[32m24-02-23 21:55:51 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_influxdb[0m
[31m24-02-23 21:54:27 ERROR (MainThread) [supervisor.backups.backup] Can't read backup tarfile /data/mounts/NASBackup/af9b22c1.tar: "filename './backup.json' not found"[0m
`

## Steps to reproduce

create a full backup or creating a backup only selecting influx addon

**Comment by sinclairpaul** [comment]
The backup functionality is within the Supervisor, not the addon itself so I doubt there is much that can be done here.

I would suggest logging the issue with the Home Assistant project, including details of your setup/configuration and the sizing of the data.
