### ISSUE TITLE
Addon installs older InfluxDB 1.x rather than current 2.x or 3.x

### ISSUE THREAD

**Issue by sammcj** [hassio-addons/addon-influxdb#325]
# Problem/Motivation

After installing this addon I found that my apps wouldn't integrated with the installed InfluxDB as it is the old 1.x version and doesn't support the current authentication mechanisms or APIs.

- InfluxDB 2 was [released in 2020](https://www.influxdata.com/blog/influxdb-2-0-open-source-is-generally-available/)
- InfluxDB 3 was [released in 2023](https://www.influxdata.com/blog/introducing-influxdb-3-0/)

## Expected behaviour

The current (major) version of InfluxDB to be installed (3.x) or previous major (2.x).

## Actual behaviour

The old (major) version of InfluxDB 1.x was installed.

## Steps to reproduce

- Install the addon.
- Try to use tools that authenticate with an org, token and bucket.
- Realise they are expecting InfluxDB >= 2.x.

## Proposed changes

Either:

- Update the addon to support InfluxDB 3.x or at least 2.x
- If the 1.x is still desired as an option either have it available as a setting - or move it to a new repo or branch such as addon-influxdb-legacy or something along those lines.

**Comment by frenck** [comment]
Closing this, as this is InfluxDB 1, not 2 or 3 (they are fundamentally different).
