### ISSUE TITLE
Runtime error - invalid memory address or nill pointer dereference

### ISSUE THREAD

**Issue by ghulleman** [hassio-addons/addon-influxdb#329]
# Problem/Motivation
With a flux query, an aggregate window with fn:max yields results, but a sum gives a "panic: runtime error: invalid memory address or nill dereference

Failes:
from(bucket: "retentiondb/infinite")
  |> range(start: -1y)
  |> filter(fn: (r) => r["_measurement"] == "Wh")
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["entity_id"] == "sb3_6_1av_40_563_daily_yield")
  |> aggregateWindow(every: 1mo, fn:sum)

<img width="932" alt="2024-03-28_21-29-08" src="https://github.com/hassio-addons/addon-influxdb/assets/100074494/39902cf9-abe5-432f-85a9-5e688ac5e579">

Works:
from(bucket: "retentiondb/infinite")
  |> range(start: -1y)
  |> filter(fn: (r) => r["_measurement"] == "Wh")
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["entity_id"] == "sb3_6_1av_40_563_daily_yield")
  |> aggregateWindow(every: 1mo, fn:max)
Only difference is the 'fn:max' / 'fn:sum'

<img width="919" alt="2024-03-28_21-28-36" src="https://github.com/hassio-addons/addon-influxdb/assets/100074494/872b8530-234c-4e0b-99a0-f4d0ecdf473b">

Found https://github.com/influxdata/influxdb/issues/21649 (not this addon), more people have this issue. 

## Expected behavior

Expect to get a bar graph with a total per month of generated kWh of a converter. 

## Actual behavior
Gives a "panic: runtime error: invalid memory address or nill dereference"

## Steps to reproduce
- Create a database 'rententiondb' with a retention policy 'infinite'.
- Create a database 'temp_import'
- Write data via influx addon to temp_import database, set precision to 's'
[influx upload.txt](https://github.com/hassio-addons/addon-influxdb/files/14794978/influx.upload.txt)
- Using the explorer window, execute "SELECT * INTO retentiondb.infinite.Wh FROM import_temp.autogen.Wh group by *" to import data to rentention/infinite. 
- Use explorer window, execute flux query:
from(bucket: "retentiondb/infinite")
  |> range(start: -1y)
  |> filter(fn: (r) => r["_measurement"] == "Wh")
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["entity_id"] == "sb3_6_1av_40_563_daily_yield")
  |> aggregateWindow(every: 1mo, fn:sum)

**Comment by lldaedalusll** [comment]
I think I did run into this as well. Suggested fix from influx forum is only to upgrade to latest influx 2.x.
