### ISSUE TITLE
Value 0 seems to be not forwarded in influxdb / Issue wit no changes when new day starts

### ISSUE THREAD

**Issue by MB1983k** [hassio-addons/addon-influxdb#330]
I am using influxdb with Grafana and I do see 2 issues - maybe someone has any idea how to solve it…

When values changes to 0 it seems that 0 is not forwarded to influxdb. E.g. I am forwarding the current Power from my go-e Chargers to influxdb and it will never change back to 0.

As soon as a new day is started the values are basically unknown to Grafana until the value is changed. Is it possible to force writing data into influxdb at a predefined time?

**Comment by frenck** [comment]
Your question seems related to Home Assistant and not InfluxDB or Grafana.

Closing the issue on this end, as this is not limited by the add-on.


../Frenck
