### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by somik321** [hassio-addons/addon-influxdb#338]
#Problem/Motivation
High CPU usage 100%-200%
![image](https://github.com/hassio-addons/addon-influxdb/assets/56112388/60729e2e-352c-4b0f-a62d-60eccb2d2906)

## Expected behavior
CPU load should be 5-10%

## Actual behavior
The settings helped only temporarily:
- name: INFLUXDB_MONITOR_STORE_ENABLED
 value: "false"
After installing this setting, the CPU load dropped to 7%
After 3 weeks the load increased again to 100%-200%

## Steps to reproduce
Rpi 3, 1 Mb RAM, 32 Gb SD
Swap 1 gb
HA Supervisor 2024.06.0
Core 2024.4.2
InfluxDB addon 5.0.0
DB influxdb ~1.2 gb, duration 1200d

## Proposed changes
We need to find what is consuming resources and issue a patch or describe the setting.

**Comment by sinclairpaul** [comment]
> DB influxdb ~1.2 gb, duration 1200d

> Rpi 3, 1 Mb RAM, 32 Gb SD

I think you may have unrealistic expectations on the hardware you are running, I would suggest shrinking your data size, and look at the queries you are running against it.

**Comment by somik321** [comment]
> > DB influxdb ~1.2 gb, duration 1200d
> 
> > Rpi 3, 1 Mb RAM, 32 Gb SD
> 
> I think you may have unrealistic expectations on the hardware you are running, I would suggest shrinking your data size, and look at the queries you are running against it.

The database became a little larger and the load increased sharply and significantly.
A little data from the smart home is written to the database; it is read occasionally, but even now, under high load, plotting is done quite quickly.
There is some problem in the addon

**Comment by somik321** [comment]
I looked for a solution to the problem on the Internet - people have a similar problem on powerful equipment
