### ISSUE TITLE
Issue "ngx_slab_alloc() failed: no memory"

### ISSUE THREAD

**Issue by garfield1964** [hassio-addons/addon-influxdb#351]
Just installed addon Influxdb Version 5.0.0 on Home Assistant 2024.9.2 and got issue: 

**[crit] 403#403: ngx_slab_alloc() failed: no memory**

Here is my log snipplet:

_[08:12:03] INFO: Starting NGINX...
2024/09/21 08:12:03 [crit] 403#403: ngx_slab_alloc() failed: no memory
[08:12:03] WARNING: NGINX crashed, halting add-on
[08:12:03] INFO: NGINX stopped, restarting...
s6-rc: info: service legacy-services: stopping
[tcp] 2024/09/21 08:12:03 tcp.Mux: Listener at 127.0.0.1:8088 failed failed to accept a connection, closing all listeners - accept tcp 127.0.0.1:8088: use of closed network connection
[08:12:03] INFO: Kapacitor stopped, restarting...
[08:12:03] INFO: InfluxDB stopped, restarting...
[08:12:03] INFO: Chronograf stopped, restarting...
s6-rc: info: service legacy-services successfully stopped_

Can anyone give some help?

**Comment by sinclairpaul** [comment]
What is your OS?, can you post the entry from the log with the OS/Hardware details?

**Comment by garfield1964** [comment]
Sorry for my delay.

here my details

Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 5.0.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2024.9.3
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

**Comment by sinclairpaul** [comment]
See #321 #334 

It's an issue with the lua module used under nginx and the changes to memory allocation in Bookworm on a Pi5.

**Comment by garfield1964** [comment]
Thank you very much. This [https://github.com/raspberrypi/bookworm-feedback/issues/107#issuecomment-1773810662](url) worked fine for me (setting kernel)

**Comment by garfield1964** [comment]
> See #321 #334
> 
> It's an issue with the lua module used under nginx and the changes to memory allocation in Bookworm on a Pi5.

Thank you so much. Worked fine setting kernel [#321]
