### ISSUE TITLE
Update InfluxDB add-on to Support InfluxDB v2

### ISSUE THREAD

**Issue by StevenSlaa** [hassio-addons/addon-influxdb#355]
### Problem
The current InfluxDB add-on in Home Assistant supports only InfluxDB v1.x, which lacks compatibility with newer installations using InfluxDB v2. InfluxDB v2 brings enhanced performance, security, and new features that are beneficial for users but currently unsupported in Home Assistant.

### Feature Request
Please update the InfluxDB add-on to support InfluxDB v2. This update should enable Home Assistant to communicate with InfluxDB v2 using its updated API, token-based authentication, and bucket system.

### Requirements
1. **Authentication**: Support for InfluxDB v2’s token-based authentication, replacing the legacy username/password setup.
2. **Bucket Support**: Compatibility with InfluxDB v2’s bucket structure instead of the database/retention policy model used in v1.
3. **API Compatibility**: integration with the InfluxDB v2 API endpoints.

### Benefits
- **Enhanced Security**: Token-based authentication provides a more secure way to interact with InfluxDB.
- **Future-Proofing**: Supporting InfluxDB v2 prepares Home Assistant users for future updates from InfluxDB.
- **Improved Performance**: InfluxDB v2 is optimized for faster queries and higher performance, which will benefit data-heavy installations.

### Additional Context
- InfluxDB v2 has been widely adopted, and many users are migrating to it.
- Token-based authentication and bucket structures are now standard in InfluxDB v2, which differs from the authentication method in InfluxDB v1.x.
  
### Suggested Solution
1. Bump InfluxDB version to 2.
2. Provide migration guidance for existing users upgrading from InfluxDB v1 to v2.

### References
- [InfluxDB v2 API Documentation](https://docs.influxdata.com/influxdb/v2.0/api/)
- [InfluxDB v2 Migration Guide](https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/)

**Thank you for considering this feature request!**

**Comment by StevenSlaa** [comment]
Added [pull-request](https://github.com/hassio-addons/addon-influxdb/pull/356)

**Comment by peterniebert** [comment]
I agree that V2 is absolutely necessary, but because of major incompatibilities (notably concerning the GUI), it is necessary to have a separate add-on. People will then be able to migrate and eventually, support for V1 can be stopped.

However, I started to work on an add-on myself (my second), but because of the GUI with HA integration, it is not as simple as snapping your fingers and it went on standby. It will require a bit of work (not that much either).
