### ISSUE TITLE
Starting NGINX crashes with ngx_slab_alloc() failed: no memory

### ISSUE THREAD

**Issue by Paperone80** [hassio-addons/addon-influxdb#358]
# Problem/Motivation
```
[08:18:42] INFO: Starting NGINX...
2024/11/09 08:18:42 [crit] 405#405: ngx_slab_alloc() failed: no memory
[08:18:42] WARNING: NGINX crashed, halting add-on
[08:18:42] INFO: NGINX stopped, restarting...
s6-rc: info: service legacy-services: stopping
[tcp] 2024/11/09 08:18:42 tcp.Mux: Listener at 127.0.0.1:8088 failed failed to accept a connection, closing all listeners - accept tcp 127.0.0.1:8088: use of closed network connection
[08:18:42] INFO: InfluxDB stopped, restarting...
```

## Expected behavior

Should start ....

## Actual behavior

**NGINX crashed, halting add-on**

## Steps to reproduce

```
-----------------------------------------------------------
 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 5.0.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2024.11.1
 Home Assistant Supervisor: 2024.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

## Proposed changes

No workaround found yet.

**Comment by sinclairpaul** [comment]
#351 #321 #334

**Comment by Paperone80** [comment]
@sinclairpaul, thanks for looking at the issue. 

With your references to the other issues, I actually found a workaround. 

The problem is the change to 16K page size as default for the Raspberry Pi OS kernel on Raspberry Pi 5. Changing back to the linux kernel with 4K page size and reboot, started the InfluxDB add-on again.

```
uname -a
```
> Linux raspberrypi 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

```
getconf PAGESIZE
```
> 16384

```
sudo nano /boot/firmware/config.txt 
```
Add the following line at top:
```
kernel=kernel8.img
```
Check that you have kernel8.img file in the right place:
```
sudo ls -lha /boot/firmware/ | grep kernel8.img
```
> -rwxr-xr-x 1 root root 8.9M Oct 13 00:34 kernel8.img

```
sudo reboot
```
Background links around Linux page size and NGINX ngx_slab_alloc:
[Link 1 ](https://pimylifeup.com/raspberry-pi-page-size/#:~:text=Starting%20with%20the%20Raspberry%20Pi,processor%20will%20need%20to%20perform.), [Link 2](https://medium.com/@openresty/how-openresty-and-nginx-shared-memory-zones-consume-ram-31d4a6ced290), [Link 3](https://forum.nginx.org/read.php?29,240420,240420#msg-240420), [Link 4](https://groups.google.com/g/nginxpushstream/c/ehjPprIR3RI?pli=1)
