### ISSUE TITLE
User cannot be created with certain passwords

### ISSUE THREAD

**Issue by Trojafux** [hassio-addons/addon-influxdb#362]
# Problem/Motivation

> (Why the issue was filed)
I installed influxdb on Home Assitant yesterday. Creating a new user failed several times until I modified the password of the newly to be created user.

## Expected behavior

> (What you expected to happen)
Any strong password should be accepted or password rules should clearly be stated.

## Actual behavior

> (What actually happened)
Several error messages occured that were related to the acutual string of the password for the new user. It seems the strings were interpreted instead.

time="2024-12-24T23:48:17+01:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found |, expected ; at line 1, char 47" component=server http_status =400
time="2024-12-24T23:48:17+01:00" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:57114" response_time="466.954µs" status=400
time="2024-12-24T23:48:41+01:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found |, expected ; at line 1, char 47" component=server http_status =400
time="2024-12-24T23:48:41+01:00" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:55196" response_time="403.511µs" status=400
time="2024-12-24T23:50:25+01:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found \\6, expected string at line 1, char 50" component=server http_status =400
time="2024-12-24T23:50:25+01:00" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:56436" response_time="398.027µs" status=400
time="2024-12-24T23:52:14+01:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found |, expected ; at line 1, char 47" component=server http_status =400
time="2024-12-24T23:52:14+01:00" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:38534" response_time="422.711µs" status=400
time="2024-12-24T23:57:45+01:00" level=info msg="Response: OK" component=server method=POST remote_addr="127.0.0.1:50400" response_time="759.353µs" status=200
time="2024-12-24T23:58:22+01:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found |, expected ; at line 1, char 47" component=server http_status =400
time="2024-12-24T23:58:22+01:00" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:35962" response_time="459.247µs" status=400
time="2024-12-24T23:58:56+01:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found |, expected ; at line 1, char 47" component=server http_status =400
time="2024-12-24T23:58:56+01:00" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:54872" response_time="403.141µs" status=400
time="2024-12-25T00:04:10+01:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found |, expected ; at line 1, char 47" component=server http_status =400
time="2024-12-25T00:04:10+01:00" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:54400" response_time="456.485µs" status=400
time="2024-12-25T00:04:26+01:00" level=info msg="Response: OK" component=server method=GET remote_addr="127.0.0.1:52400" response_time="36.919µs" status=200
time="2024-12-25T00:05:09+01:00" level=error msg="Error message received status code 400 from server: err: error parsing query: found A1sbMe, expected ; at line 1, char 47" component=server http_status =400
time="2024-12-25T00:05:09+01:00" level=info msg="Response: Bad Request" component=server method=POST remote_addr="127.0.0.1:53676" response_time="381.971µs" status=400

## Steps to reproduce

> (How can someone else make/see it happen)

Try these passwords that lead to errors:

pGg'|A1sbMe!^Sl&H)^Q

pGg'A1sbMe!^Sl&H)^Q

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Please see the InfluxDB documentation, in particular <https://docs.influxdata.com/influxdb/v1/troubleshooting/frequently-asked-questions/#how-do-i-include-a-single-quote-in-a-password>
