### ISSUE TITLE
So what the version of influxdb is???  1 or 2 ???

### ISSUE THREAD

**Issue by 20flint12** [hassio-addons/addon-influxdb#363]
# Problem/Motivation

Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 5.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 14.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.12.5
 Home Assistant Supervisor: 2024.12.0

Where can I specifically find out which version of the database is used in this addon?

**Comment by tjorim** [comment]
It's running [InfluxDB 1.8.10](https://github.com/hassio-addons/addon-influxdb/blob/v5.0.1/influxdb/Dockerfile#L10). Updates would show in the release changelog, last bump was done in (add-on) version 4.3.0: https://github.com/hassio-addons/addon-influxdb/releases/tag/v4.3.0.
