### ISSUE TITLE
Enabling UDP

### ISSUE THREAD

**Issue by SNoof85** [hassio-addons/addon-influxdb#39]
# Problem/Motivation

I would like to push my proxmox metrics to influxdb

## Expected behavior

UDP enabled and configurable

## Actual behavior

No UDP possible

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

## More infos/links
https://pve.proxmox.com/wiki/External_Metric_Server

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://pve.proxmox.com/wiki/External_Metric_Server">External Metric Server - Proxmox VE</a></strong></div></blockquote>

We have to configure influxdb udp like :
```
[[udp]]
  enabled = true
  bind-address = "0.0.0.0:8089"
  database = "proxmox"
  batch-size = 1000
  batch-timeout = "1s"
```

**Comment by frenck** [comment]
Sorry, I'm not making new features until InfluxDB becomes stable.

**Comment by frenck** [comment]
I forgot to add the version number, so that looked weird.

I meant InfluxDB 2.0. A lot of changes are incoming and don't want to create anymore potentially backward incompatible changes at this point.

**Comment by SNoof85** [comment]
No worries, I just managed to make it work. Nothing complex. I completly understand your point of view.
Keep on good work and see you in next stream 👍
