### ISSUE TITLE
Enable InfluxDB's new query language 'Flux'

### ISSUE THREAD

**Issue by MNicks** [hassio-addons/addon-influxdb#41]
# Problem/Motivation

Flux is InfluxData’s new functional data scripting language which is available as of InfluxDB v1.7+   Flux is still in technical preview but nevertheless it would great to have this feature available in addition to standard InfluxQL.  

## Actual behavior

Flux scripts/ queries are not supported

## Expected behavior

After activation the option to express Flux queries for example in Chronograf or Grafana become available

## Proposed changes

Enable Flux feature in `influxdb.conf` as descibed in InfluxDB's documentation ([see](https://docs.influxdata.com/flux/v0.24/introduction/installation/))

**Comment by frenck** [comment]
Added to our edge releases, will be part of the upcoming release.
