### ISSUE TITLE
 Chronograf (1.7.13) Cannot read property 'split' of null

### ISSUE THREAD

**Issue by AnthonyD42** [hassio-addons/addon-influxdb#46]
# Problem/Motivation

> I am getting an error when I click on the "Explore" icon.

## Expected behavior

> Explore should open

## Actual behavior

> I get a blank page with the message "A Chronograf error has occurred. Please report the issue here."   When I click the hyperlink (here), it takes me to the Git for influxdata / chronograf and prepopulates the issue "Chronograf (1.7.13) Cannot read property 'split' of null"

## Steps to reproduce

> Clicking the Explore icon in InfluxDB

## Proposed changes

> Searching the issues on the influxdata / chronograf Git says the issue was resolved in Chronograf (1.7.14).  Perhaps updating the Chronograf will correct the issue?
![InfluxDB Error](https://user-images.githubusercontent.com/21263818/64068378-f68acf00-cbfc-11e9-80b6-e1334a8b772c.JPG)

**Comment by tmonck** [comment]
I'm having the same issue. Running on rpi3 hassio v0.98.2. There is nothing in the addon logs indicating a problem. Nor is there anything in the system log indicating an error.

**Comment by lukasz-picur** [comment]
Having the same problem here, running hassio 0.98.2 on RPI 4.

**Comment by ocalvo** [comment]
Having the same issue running on hassio 0.98.2 on RPI 4.

**Comment by sander45** [comment]
Me too. 

However I figured out that if you log out and log in from Home Assistant it will work for a while. If I click on one of the other items on the sidebar e.g [Dashboards] and then go back to [Explore], the error occurs again. I managed to get data from the [_internal.monitor]. Though I still can’t get data from glances or HA. As I’m a newbee it could me my fault as well. still learning from the great 15 minutes instruction video of Frenck.

So my guess is that it has to do with rights/login credentials.


I re-installed hassio today again from stretch,  use the standard settings for InfluxDB, except for the SSL:

CONFIG{
  "auth": true,
  "reporting": true,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
NETWORK
Container- host-describtion
80/tcp – disabled- Web interface
8086/tcp	- 8086 - influxdb server

I run Hassio 0.98.2 on a RPI 3B+. Use several browsers including Firefox and chrome on a Windows machine.

**Comment by sander45** [comment]
Is this error from the Hassio System log relevant?

....
19-09-03 18:31:21 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_influxdb
19-09-03 18:31:22 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_influxdb
19-09-03 18:31:30 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:1337 ssl:None [Connection refused]
19-09-03 18:31:40 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.33.0:1337 ssl:None [Connection refused]

thanks for any suggestions

**Comment by tmonck** [comment]
This is working again for me after updating to the newest release 3.2.1 Thanks @frenck

**Comment by sander45** [comment]
Yep all up and running. Frenck for president

**Comment by AnthonyD42** [comment]
Thank you!!!
