### ISSUE TITLE
First start problem

### ISSUE THREAD

**Issue by ggraziotti** [hassio-addons/addon-influxdb#47]
# Problem/Motivation

Add-on do not start on first start.

my per cinfiguration:
On configurazion.yaml I added:
Influxdb:

Config
{
  "auth": true,
  "reporting": true,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

Network:

Container | Host | Description
-- | -- | --
80/tcp |   | Web interface (Not required for Hass.io Ingress)
8086/tcp |   | InfluxDB server

MySystem:

Hassio supervisor 185

Hostname | raspberrypi
-- | --
System | Raspbian GNU/Linux 10 (buster)

My log:

19-09-10 16:02:42 INFO (SyncWorker_2) [hassio.docker.interface] Clean addon_a0d7b954_influxdb application
19-09-10 16:02:43 ERROR (SyncWorker_2) [hassio.docker] Can't start addon_a0d7b954_influxdb: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_influxdb (e2369be2d64c86c57536a03ddb0f45aec369f2b66caa8bd6db538c0e3b82d8a1): Error starting userland proxy: listen tcp 0.0.0.0:8088: bind: address already in use")
19-09-10 16:03:34 INFO (SyncWorker_14) [hassio.docker.interface] Clean addon_a0d7b954_influxdb application
19-09-10 16:03:35 ERROR (SyncWorker_14) [hassio.docker] Can't start addon_a0d7b954_influxdb: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_influxdb (de70a36b6976ec5e84579cfdd3833099c01be7e0dbf008e0e1d76c31fe2638e7): Error 

Can someone help me?

**Comment by frenck** [comment]
`listen tcp 0.0.0.0:8088: bind: address already in use`

That means port 8080 is already in use by something else. Either change the port in the add-on, or change the thing that uses the port to something else.

**Comment by ggraziotti** [comment]
Tks

Il mar 10 set 2019, 20:53 Franck Nijhof <notifications@github.com> ha
scritto:
