### ISSUE TITLE
Accessesing actual influx config

### ISSUE THREAD

**Issue by Sabuto** [hassio-addons/addon-influxdb#49]
# Problem/Motivation

I am trying to access the actual config in order to get netdata working with influx db and in order to do that i need to alter some lines in the config. I know in grafana you can pass enviroment variables to do this but i don't think the same is possible in influx db. Is there any was round this or will i need to use a seperate docker file?

## Expected behavior

Have access to the actual config

## Actual behavior

Not accessable as far as i can see

## Steps to reproduce

standard hassio influxdb addon instalation

## Proposed changes

I'm not sure how this would be accomplished but thought it may be a good idea to be able to do this.

**Comment by sinclairpaul** [comment]
Environment Variables now available to configure in release 3.4.0
