### ISSUE TITLE
Unclear how to set up authentication

### ISSUE THREAD

**Issue by dp106** [hassio-addons/addon-influxdb#5]
# Problem/Motivation

Unable to connect to influxdb in hassio

INFO: Starting the Kapacitor
2018/09/18 15:50:53 Using configuration at: /etc/kapacitor/kapacitor.conf
'##:::'##::::'###::::'########:::::'###:::::'######::'####:'########::'#######::'########::
 ##::'##::::'## ##::: ##.... ##:::'## ##:::'##... ##:. ##::... ##..::'##.... ##: ##.... ##:
 ##:'##::::'##:. ##:: ##:::: ##::'##:. ##:: ##:::..::: ##::::: ##:::: ##:::: ##: ##:::: ##:
 #####::::'##:::. ##: ########::'##:::. ##: ##:::::::: ##::::: ##:::: ##:::: ##: ########::
 ##. ##::: #########: ##.....::: #########: ##:::::::: ##::::: ##:::: ##:::: ##: ##.. ##:::
 ##:. ##:: ##.... ##: ##:::::::: ##.... ##: ##::: ##:: ##::::: ##:::: ##:::: ##: ##::. ##::
 ##::. ##: ##:::: ##: ##:::::::: ##:::: ##:. ######::'####:::: ##::::. #######:: ##:::. ##:
..::::..::..:::::..::..:::::::::..:::::..:::......:::....:::::..::::::.......:::..:::::..::
ts=2018-09-18T15:50:53.715Z lvl=error msg="encountered error" service=run err="open server: open service *influxdb.Service: failed to link subscription on startup: error authorizing query: no user provided"
run: open server: open service *influxdb.Service: failed to link subscription on startup: error authorizing query: no user provided
INFO: Starting the Kapacitor

## Expected behavior

I expect to be able to open the ui from Homeassistant with auth enabled, the documentation warns about disabling this. However if trying to connect with auth enabled you get error must set up admin user first.  

## Actual behavior

In order to create the homeassistant database I had to switch auth off in order to connect. Created the database and user, re-enabled auth but now get errors again.  **Need to verify exact error this evening

## Steps to reproduce

enable Influxdb in hassio, follow instructions as per readme without doing anything else

## Proposed changes

Add documentation to set up the auth properly. I have clearly missed something but can't see anything from the docs so it is probably obvious to an expert but not to someone who hasn't done this before

**Comment by frenck** [comment]
Authentication has changed in the upcoming release.
How to connect the add-on to Home Assistant is documented (correctly) in the readme.
