### ISSUE TITLE
CPU spikes

### ISSUE THREAD

**Issue by mountwebs** [hassio-addons/addon-influxdb#51]
Ever since I installed influxDB on hass.io a month ago my cpu usage spikes every few hours. A couple of times my raspberry pi 3 has crashed, and I suspect that this might be the reason. I searched the home assistant forums, and a few other people seems to be having this same issue. 

Some people point to influxdbs self monitoring as a possible reason, and suggest that editing 
 influxdb's config might help. Is this configuration available to edit somewhere? And if not, is it possible to stop influxdb's self monitoring in another way?

The issue has been posted here:
[https://community.home-assistant.io/t/influxdb-keeps-spiking-up-cpu/125630/6](https://community.home-assistant.io/t/influxdb-keeps-spiking-up-cpu/125630/6)
and here: [https://discourse.nodered.org/t/influxdb-on-a-raspberry-pi/742](https://discourse.nodered.org/t/influxdb-on-a-raspberry-pi/742)

Issue  #49 is also related.

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/ing-med/200/65139_2.png" width="48" align="right"><div><img src="https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/optimized/3X/f/4/f42b82971fce994297fbc2b269efa248beef897b_2_32x32.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/influxdb-keeps-spiking-up-cpu/125630/6">Influxdb keeps spiking up CPU</a></strong></div><div>anyone else have an idea?</div></blockquote>
<blockquote><img src="https://aws1.discourse-cdn.com/business6/uploads/nodered/original/2X/4/4e31e726f516faf3d28cb905ee61b6165a0465a3.svg" width="48" align="right"><div><img src="https://aws1.discourse-cdn.com/business6/uploads/nodered/optimized/1X/598c4a26af3e3272e341a28c9f4adb5c75c8f5dc_2_32x32.png" height="14"> Node-RED Forum</div><div><strong><a href="https://discourse.nodered.org/t/influxdb-on-a-raspberry-pi/742">InfluxDB on a Raspberry Pi</a></strong></div><div>This is not strictly Node-Red related but I know that several people here are using InfluxDB on a Raspberry Pi in conjunction with Grafana to store data created/extracted  by Node-Red.  I discovered accidentally that InfuxDB was using a very high amount of CPU time and after a bit of searching I found that this is due to InfluxDB’s internal monitoring function. This is used for diagnosis of internal errors and can safely be turned off by changing an entry in:  /etc/influxdb/influxdb.conf  Simply...</div></blockquote>

**Comment by sinclairpaul** [comment]
Environment Variables now available to configure in release 3.4.0
