### ISSUE TITLE
Can't set new envvars

### ISSUE THREAD

**Issue by rychardeh** [hassio-addons/addon-influxdb#55]
# Problem/Motivation

Any attempt to set an envvar in the addon config fails silently (while other config entries can be modified successfully). E.g.:

`{
  "auth": true,
  "reporting": true,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "envvars": [
    {
      "name": "INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE",
      "value": "512m"
    }
  ],
  "log_level": "debug"
}`

## Expected behavior

New envvars section accepted as valid config.

## Actual behavior

Config panel is not refreshed but, leaving and re-entering addon management page shows that config remains unmodified.

## Steps to reproduce

Cut and paste above example of envvars, hit

**Comment by sinclairpaul** [comment]
Unfortunately there was an issue in my original PR, please hold on for the next release.
