### ISSUE TITLE
Feature Request: restart influxd on crash instead of exiting and stopping the addon.

### ISSUE THREAD

**Issue by vandalon** [hassio-addons/addon-influxdb#58]
# Problem/Motivation

It sometimes happens influxd crashes because of a momory issue and then the addon just stops, 

## Expected behavior

Restart influxd

## Actual behavior

addon stops

## Steps to reproduce

kill influxd

## Proposed changes

Use a wrapper to restart influxd on crash after a cool-down period of several seconds.

**Comment by frenck** [comment]
Docker containers should crash if the application inside them stops working. That is part of the design and best practices of Docker.

Making it restart over and over again, may cause new issues (e.g., other things will start to crash in case the OOM killer starts bashing around).

This request will most certainly not be implemented in this add-on.
