### ISSUE TITLE
unable to change user permissions

### ISSUE THREAD

**Issue by doppiaemme** [hassio-addons/addon-influxdb#60]
# Problem/Motivation

After installing the addon following the instruction, I can create a user but the default permission is set to NONE and it's not possible to change it

## Expected behavior

It should be possible to set it to ALL

## Actual behavior

When selecting ALL it doesn't save it

## Steps to reproduce

Install the latest addons and follow the instructions

![image](https://user-images.githubusercontent.com/3978350/72082791-05973180-3301-11ea-9d7d-255d75eb89d2.png)

**Comment by frenck** [comment]
You have to push Apply.

![2020-01-09 17 03 50](https://user-images.githubusercontent.com/195327/72083409-13998200-3302-11ea-9508-17c5d7f9ca6b.gif)

**Comment by doppiaemme** [comment]
Sorry, my fault,  I overlooked that button.

please close this non-issue :-)

**Comment by frenck** [comment]
No problem m8!
