### ISSUE TITLE
influxdb cannot start 3.5.1

### ISSUE THREAD

**Issue by vhristev** [hassio-addons/addon-influxdb#61]
I tried to troubleshoot it but at some point ( i don't know when) influxdb just stop working. I didn't re-install it because I don't want to lose my config and DB. From log messages, i cannot understand why service cannot start. The issue is not caused by InfluxDB version I have that issue from 2-3 versions back. 

Home Assistant: 0.102.3
InfluxDB: 3.5.1

# Problem/Motivation
 influxdb cannot start.

## Expected behavior
influxdv should start normally 

## Actual behavior
 influxdb cannot start.

## Steps to reproduce
From home assistant addons select influxDb and click start. 
> (How can someone else make/see it happen)

`goroutine 642 [runnable]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*encoder).Write(0x2ceec40, 0xf0f765e6, 0x15e6c31a)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/timestamp.go:81 +0xb4
github.com/influxdata/influxdb/tsdb/engine/tsm1.encodeStringBlockUsing(0x0, 0x0, 0x0, 0xc55bf40, 0x3e8, 0xc18, 0x1ab2c60, 0x2ceec40, 0xbe10a000, 0x1452, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:865 +0x74
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).encode.func1(0x16f364a8, 0x1, 0x428, 0x29f7780)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1967 +0x654
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).encode
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1921 +0x80

goroutine 621 [IO wait]:
internal/poll.runtime_pollWait(0xa6cebf30, 0x72, 0xffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x48
internal/poll.(*pollDesc).wait(0x16f9c244, 0x72, 0xe00, 0xe6f, 0xffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x80
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x16f9c230, 0x817e000, 0xe6f, 0xe6f, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x184
net.(*netFD).Read(0x16f9c230, 0x817e000, 0xe6f, 0xe6f, 0x1b0c0, 0x1b96c, 0x18f846c0)
	/usr/local/go/src/net/fd_unix.go:202 +0x38
net.(*conn).Read(0x1687eb60, 0x817e000, 0xe6f, 0xe6f, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x5c
crypto/tls.(*atLeastReader).Read(0x18f846c0, 0x817e000, 0xe6f, 0xe6f, 0x18148, 0x267d34, 0x1aa80b8)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x78
bytes.(*Buffer).ReadFrom(0x322a960, 0x1aa4f08, 0x18f846c0, 0x5d, 0x266700, 0xd42168, 0xe79538)
	/usr/local/go/src/bytes/buffer.go:207 +0xac
crypto/tls.(*Conn).readFromUntil(0x322a800, 0x1aa80b8, 0x1687eb60, 0x5, 0x1687eb60, 0x1a7a14c)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xd8
crypto/tls.(*Conn).readRecordOrCCS(0x322a800, 0x18e6e00, 0x322a8b0, 0x3ed65297)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x108
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0x322a800, 0x192d6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x140
net/http.(*persistConn).Read(0x16faa0a0, 0x192d6000, 0x1000, 0x1000, 0x10228f24, 0x2, 0x2)
	/usr/local/go/src/net/http/transport.go:1524 +0x1c0
bufio.(*Reader).fill(0x185b6330)
	/usr/local/go/src/bufio/bufio.go:100 +0x114
bufio.(*Reader).Peek(0x185b6330, 0x1, 0x2, 0x0, 0x0, 0x13793f00, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x38
net/http.(*persistConn).readLoop(0x16faa0a0)
	/usr/local/go/src/net/http/transport.go:1677 +0x168
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1357 +0x924

goroutine 641 [runnable]:
github.com/influxdata/influxdb/vendor/github.com/jwilder/encoding/simple8b.canPack(0x2dc7000, 0xf0, 0xf0, 0x14, 0x3, 0x6e000)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/jwilder/encoding/simple8b/encoding.go:444 +0x184
github.com/influxdata/influxdb/vendor/github.com/jwilder/encoding/simple8b.Encode(0x2dc7000, 0xf0, 0xf0, 0x5827eccd, 0xf0000002, 0x1, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/jwilder/encoding/simple8b/encoding.go:315 +0x1bc
github.com/influxdata/influxdb/vendor/github.com/jwilder/encoding/simple8b.(*Encoder).flush(0x2b46d50, 0x2dc7008, 0x778)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/jwilder/encoding/simple8b/encoding.go:101 +0x68
github.com/influxdata/influxdb/vendor/github.com/jwilder/encoding/simple8b.(*Encoder).Write(0x2b46d50, 0x53c96323, 0x2, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/vendor/github.com/jwilder/encoding/simple8b/encoding.go:78 +0xf8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*encoder).encodePacked(0x2ceec20, 0x1, 0x0, 0x28c6000, 0x3e8, 0x3e8, 0x28c6000, 0x3e8, 0x3e8, 0x16f1e910, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/timestamp.go:151 +0x3d4
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*encoder).Bytes(0x2ceec20, 0x1f159e2d, 0x3fb40bbc, 0x2843300, 0xc1e734, 0x4fddbc0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/timestamp.go:138 +0xec
github.com/influxdata/influxdb/tsdb/engine/tsm1.encodeFloatBlockUsing(0x0, 0x0, 0x0, 0x1265bf40, 0x3e8, 0xc18, 0x1ab2c60, 0x2ceec20, 0x1171a0c0, 0xbe1ae000, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:382 +0xf0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).encode.func1(0x16f364a8, 0x1, 0x428, 0x29f7780)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1959 +0x2ec
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).encode
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1921 +0x80

goroutine 622 [select]:
net/http.(*persistConn).writeLoop(0x16faa0a0)
	/usr/local/go/src/net/http/transport.go:1976 +0xb8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1358 +0x940

goroutine 288 [runnable]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*encoder).Write(0x2ceec00, 0xed1d047, 0x15e6c296)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/timestamp.go:81 +0xb4
github.com/influxdata/influxdb/tsdb/engine/tsm1.encodeStringBlockUsing(0x0, 0x0, 0x0, 0xe31ff40, 0x3e8, 0xc18, 0x1ab2c60, 0x2ceec00, 0xbe108000, 0x1950, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/encoding.go:865 +0x74
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).encode.func1(0x16f364a8, 0x1, 0x428, 0x29f7780)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1967 +0x654
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).encode
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1921 +0x80

goroutine 286 [chan receive]:
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*cacheKeyIterator).Next(0x29f7780, 0x4002bb)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:2006 +0xe8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).write(0x28d3b00, 0x7a08780, 0x42, 0x1abaf08, 0x29f7780, 0xe95c01, 0x0, 0x0)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1128 +0x148
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).writeNewFiles(0x28d3b00, 0x8, 0x1, 0x0, 0x0, 0x0, 0x1abaf08, 0x29f7780, 0x1, 0x0, ...)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:1032 +0x144
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).WriteSnapshot.func1(0x131b4fc0, 0x28d3b00, 0x16f36474, 0x29f7740, 0x2887e00)
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:847 +0x94
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Compactor).WriteSnapshot
	/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/compact.go:845 +0x16c
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal`

**Comment by rychardeh** [comment]
Take a look at https://github.com/hassio-addons/addon-influxdb/issues/53.  It looks like it might be the same problem.

**Comment by vhristev** [comment]
Thank you I read that one back in the days but i totally forgot to follow up there. It seems im going to use my Synology for influxDB.
