### ISSUE TITLE
Allow more environment variables to fix issues with kapacitor and chronograf

### ISSUE THREAD

**Issue by MoHf7f4** [hassio-addons/addon-influxdb#62]
# Problem/Motivation

Environment variables can't be set for all influx related services.

addon-influxdb/influxdb/config.json has a regex for env variables
 "name": "match(^INFLUXDB_([A-Z0-9_])+$)"

The addon is also installing kapacitor and chronograf, their environment variables begin with KAPACITOR_ and for Chronograf the variables are all over the place, some influx some for all the other services it can use, it's not feasible to try and make a regex for all of them since it appears they will change depending on services implemented.

So for me, I'm enabling SSL for influx input, this seems to break kapacitor and chronograf that were installed by default.  They go into a loop of trying to list the databases and consume all cpu and do nothing.

I could fix this by setting environment variables to fix their behavior.

## Expected behavior

Allow any environment variable to be set.  Not just what starts with Influxdb.

## Actual behavior

INFLUXDB_ variables are all that's allowed

try setting:
KAPACITOR_INFLUXDB_0_URLS_0="https://localhost:8086"
KAPACITOR_INFLUXDB_0_SSL_CERT="/etc/ssl/influxdb-selfsigned.crt"
KAPACITOR_INFLUXDB_0_SSL_KEY="/etc/ssl/influxdb-selfsigned.key"
KAPACITOR_INFLUXDB_0_INSECURE_SKIP_VERIFY=true
KAPACITOR_INFLUXDB_0_SUBSCRIPTION_PROTOCOL="https"

> (How can someone else make/see it happen)

## Proposed changes

Change:
"name": "match(^INFLUXDB_([A-Z0-9_])+$)"
to:
"name": "match(^([A-Z0-9_])+$)"

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Allow people to configure the service beyond the limiting defaults.  Giving us the ability to set environment variables has been extremely helpful (I thank you so much for that).  It was too limited in scope.

**Comment by sinclairpaul** [comment]
The challenge with this is how far do we go with the customisation, and at which point you may as well just run your own containers.  I'll let @frenck decide, but I personally wouldn't add this in.  The influx env vars were added as in some use cases the addon could fail to start or cause performance issues in some environments.

Just as a side note in your use case, the traffic is all local to the container.

**Comment by MoHf7f4** [comment]
I'm sending metrics to influx from outside the containers.

If home assistant add-ons are only supposed to be used by home assistant
I'd agree with you.

**Comment by sinclairpaul** [comment]
So it would be fair to say that the requirements is to allow SSL access to Influx?, it looks like this existed in the past.

**Comment by MoHf7f4** [comment]
It would be nice and it's recommended in influx docs.

**Comment by sinclairpaul** [comment]
Thanks, it is listed in the known issues, I am sure Frenck would have more details on the challenges.

**Comment by frenck** [comment]
This add-on will not receive more features right now, because we are getting close to an InfluxDB 2.0 release, which changes everything.

Introducing this suggested feature would render useless and an instant breaking change.

**Comment by MoHf7f4** [comment]
Can you please just change the one regex in the package to allow people to
add their own env variables not beginning with influx?  It's silly we'd
need to fork to change one line in a config.
