### ISSUE TITLE
Feature request: Ability to write data to InfluxDB Cloud

### ISSUE THREAD

**Issue by sridharangopal** [hassio-addons/addon-influxdb#63]
# Problem/Motivation

This is a feature request. It would be very useful if this addon supports writing the time-series data InfluxDB Cloud.

## Expected behavior

Able to configure the addon to write to InfluxDB Cloud.

## Actual behavior

Unable to configure the addon to write to a DB on InfluxDB Cloud.

## Steps to reproduce

Not applicable

## Proposed changes

None yet. But looking into it.

**Comment by frenck** [comment]
Feel free to configure your Home Assistant to write to the cloud.
Add-ons are about local services.
