### ISSUE TITLE
X-Frame-Options: Deny Issue

### ISSUE THREAD

**Issue by jreed509** [hassio-addons/addon-influxdb#64]
When I attempt to access InfluxDB using ingress I receive a "my.domain.com refused to connect" message in the iframe. 

Looking into chrome's logs there's a X-Frame-Options error:
`Refused to display "https://my.domain.com/api/hassio_ingress/####" in a frame becasue it set 'X-Frame-Options' to 'deny'.`

I'm running hassio on an Ubuntu server and I use traefik to handle my docker reverse proxies. In my reverse proxy config, I have it configured to set the `X-Frame-Options` header to `SAMEORIGIN` for all hassio traffic and this works great with all other hassio apps using ingress.

Does influxdb handle requests differently than most other addons so that my custom header is being overwritten somewhere?

**Comment by frenck** [comment]
We do not set such an option. If we did, ingress would not have worked at all.
