### ISSUE TITLE
Exec format error qemuarm-64

### ISSUE THREAD

**Issue by povlhp** [hassio-addons/addon-influxdb#65]
# Problem/Motivation
InfluxDB will not start on hassocks.io built to qemuarm-64 target.

```
[17:00:42] INFO: Starting the Kapacitor
./run: line 33: /usr/bin/kapacitord: cannot execute binary file: Exec format error
```

Problem is capacitor is built as 32-bit app.
`kapacitor: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped`

## Expected behavior

That influxdb starts (all binaries built correct)

## Actual behavior

Not starting

## Steps to reproduce

Try to install and launch InfluxDB on qemuarm-64 target.

## Proposed changes

Download page does NOT list arm64 target, only armhf (aka 32-bit). The downloaded version is the 32-bit version. From what I can see, some never aarch64 CPUs will not run 32-bit instructions. So hardware limitation. I will try to put pressure on influxdb.

**Comment by povlhp** [comment]
Did some more research, trying to compile capacitor by hand, it uses Google go, which seems to also serve armhf when requesting arm64. So the troubles all traces back to google.

**Comment by frenck** [comment]
> From what I can see, some never aarch64 CPUs will not run 32-bit instructions. So hardware limitation.

That is correct, the add-on installs the packages provided by Grafana, which works on most aarch64 devices. However, there is always a limitation if the CPU supports the 32 bits mode. For Home Assistant supported devices, that is no issue, with custom devices, you might end up with these types of things, which from an add-on perspective, can't be handled in all cases.
