### ISSUE TITLE
Compile issues arm64

### ISSUE THREAD

**Issue by povlhp** [hassio-addons/addon-influxdb#67]
Cloning the repository, and compiling for arm64 / aarch 64, I have 2 issues:
One is that BUILD_ARCH is inside the docker file. Shouldn't this be set outside the dockerfile, and inherited ? I can not clone as a local addon and compile.
```
# Setup base system
ARG BUILD_ARCH=amd64
```

The other is, that I can not find the lua 1.6, has to be 1.7 (likely to match the nginx commit already added a few days ago).
```
        libnginx-mod-http-lua=1.14.0-0ubuntu1.6 \
```

**Comment by frenck** [comment]
The architecture is a build argument, you can override it during build time by passing them into your build command.

However, these add-ons are not meant to be built manually, so I'm not sure why you ask about that.

The NGINX LUA module might be outdated, sure, will be picked up during maintenance.

**Comment by povlhp** [comment]
Thought I could just clone and use as base. 
As mentioned before influxdb arm64 comes with arm32 binaries. Needed to copy right ones on top of the bad. 
Got the chronograph patch comitted. Kapacitor has commit backlog. So I will likely use my own build for some months.

**Comment by frenck** [comment]
You can use any add-on as a base for other add-ons, however, the builds are initiated by the Supervisor, which passes in the build arguments needed.

**Comment by povlhp** [comment]
My qemuarm-64 installation failed building a git clone installed into local. Error 100 in building docker image.
When I deleted/changed (not sure which) BUILD_ARCH in the cloned addons-influxdb in the addons/local folder, then supervisor would build it correct.  
Arm64 seems to not override the BUILD_ARCH inside Dockerfile.

**Comment by frenck** [comment]
Sorry to hear you are having issue, however, this is what it has been for 2 years, and I have been using for many add-ons. The core add-ons do not even have a default...

Yes, it overrides, if not, it is a bug that should be reported @ Supervisor. Just clicked a quick local add-on on an ARM device to validate, but cannot reproduce it.

That said, that is kinda out of scope for this add-on.
