### ISSUE TITLE
Wrong kapacitor architecture (I think...)

### ISSUE THREAD

**Issue by MadDoct** [hassio-addons/addon-influxdb#69]
# Problem/Motivation

Influxdb add-on won't start on aarch64 (arm64)

## Expected behavior

Start and become available

## Actual behavior

Stops with error

## Steps to reproduce

Start the add-on on an arm64 machine

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

## Log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 3.6.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (aarch64 / qemuarm-64)
 Home Assistant Core: 0.106.4
 Home Assistant Supervisor: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] create-users.sh: executing... 
[cont-init.d] create-users.sh: exited 0.
[cont-init.d] influxdb.sh: executing... 
[cont-init.d] influxdb.sh: exited 0.
[cont-init.d] kapacitor.sh: executing... 
[cont-init.d] kapacitor.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:20:36] INFO: Starting the InfluxDB...
[12:20:36] INFO: Kapacitor is waiting until InfluxDB is available...
[12:20:36] INFO: Chronograf is waiting until InfluxDB is available...
[12:21:24] INFO: Starting Chronograf...
[12:21:25] INFO: Starting the Kapacitor
./run: line 33: /usr/bin/kapacitord: cannot execute binary file: Exec format error
./run: line 33: /usr/bin/kapacitord: Success
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment]
Could you please provide details on the hardware used?

**Comment by MadDoct** [comment]
I'm using an s905x3 (arm64) based box running armbian buster.

**Comment by MadDoct** [comment]
I've reviewed the code and it really doesn't seem to be what I suspected... What do you think is the problem?

**Comment by MadDoct** [comment]
Problem persists after update to 3.6.1...
