### ISSUE TITLE
1.7.4 Web UI button missing

### ISSUE THREAD

**Issue by Cloolalang** [hassio-addons/addon-influxdb#74]
# Problem/Motivation

Hassio 0.105.4
R Pi 3B+
Influxdb Addon 1.7.4

> Attempting to install Influxdb Addon on a remote machine (via NabuCasa)
Following instructions here:
https://community.home-assistant.io/t/home-assistant-community-add-on-influxdb/54491
4. Click the “OPEN WEB UI” button!

## Expected behavior

> In the Hassio UI, Hass.io: add-on details for InfluxDb Addon page, expected to see link:
"OPEN WEB UI"

## Actual behavior

> In the Hassio UI, Hass.io: add-on details for InfluxDb Addon page, the link:
"OPEN WEB UI"  is missing which inconsistent with the instructions/docs.

## Steps to reproduce

> Install Influxdb Addon 1.7.4 via remote interface and attempt to access Influxdb Web UI.
Not sure if this also occurs on local access to.

## Proposed changes

Non

**Comment by frenck** [comment]
I cannot reproduce this. A lot of fixes in the Supervisor has been done in the meantime.

Whatever the case, the button is not controlled by the add-on, but the Supervisor/Frontend of Home Assistant. If this issue persists, please report the issues @ Home Assistant.

Thanks! 👍
