### ISSUE TITLE
Can’t remove/disable influxdb addon

### ISSUE THREAD

**Issue by iz3man** [hassio-addons/addon-influxdb#75]
arch: armv7
channel: stable
hassos: "3.12"
homeassistant: 0.107.7
hostname: hassio
logging: info
machine: raspberrypi4
supervisor: "214"
supported_arch:
- armv7
- armhf

# Problem/Motivation

Tried to remove addon, but some residues seem still existent and produce errors 

## Expected behavior

Installed trough add-ons, in HASSIO, worked fine, but wanted to de-install again as it was not needed anymore.

## Actual behavior

This is the error I receive:

Logger: homeassistant.components.influxdb
Source: components/influxdb/__init__.py:173
Integration: influxdb (documentation, issues)
First occurred: 4:45:10 PM (1 occurrences)
Last logged: 4:45:10 PM

Database host is not accessible due to 'HTTPConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb015d230>: Failed to establish a new connection: [Errno -3] Try again'))', please check your entries in the configuration file (host, port, etc.) and verify that the database exists and is READ/WRITE. Retrying again in 60 seconds.

## Steps to reproduce

Install the addon and try to remove it again.

**Comment by iz3man** [comment]
https://community.home-assistant.io/t/cant-remove-disable-influxdb-addon/184370

**Comment by frenck** [comment]
That message is not from the add-on, but from the Home Assistant Core...

Please also clean up your own configuration. 👍

**Comment by iz3man** [comment]
Thanks @frenck. The problem is: WHERE is this configuration. I did NOT (knowingly) add anything manually when installing the add-on. So where could that message come from?

**Comment by frenck** [comment]
I don't know, this is manually configured by you.

The add-on does not configure or modify the Home Assistant Core configuration.

**Comment by iz3man** [comment]
@frenck you say this is from core, and i believe you, as i have no experience with programming.

Could you tell me why it says, so I can dig deeper:

Logger: homeassistant.components.influxdb
Source: components/influxdb/init.py:173
Integration: influxdb (documentation, issues)

Everything shows INFLUX. Could you please tell my what init.py in line 173 wants to do?
The word influx is not existent in my whole (editable) configuration.

**Comment by frenck** [comment]
@iz3man Please head over to Home Assistant.
Your question is NOT about the add-on. This is Home Assistant throwing that message.
The add-on does not configure, modify or alter any Home Assistant configuration. Any changes it is complaining about now, is your own doing, not the add-on.
