### ISSUE TITLE
Add option store-enabled = false to influxdb.conf

### ISSUE THREAD

**Issue by L2v2P** [hassio-addons/addon-influxdb#76]
# Problem/Motivation
It seems that InfluxDB may start to use excessive CPU and RAM resources on a Raspberry PI after a while (see [this issue](https://github.com/influxdata/influxdb/issues/9475)). I have quite a lot of sensor that log to InfluxDB every 10 seconds. After each restart of InfluxDB within 3 days or so HA starts to slow down significantly and InfluxDB seems to be the culprit (also see [my comment](https://community.home-assistant.io/t/influxdb-on-hassio-cpu-usage/166162/5) on the forum).

## Proposed changes
As suggested by the InfluxDB team ([link](https://github.com/influxdata/influxdb/issues/9475#issuecomment-375773775)) a possible solution is "to disable the internal monitor" by adding the following to the influxdb.conf file:
```
[monitor]
   store-enabled = false
```
For me this has solved the issue of high CPU and RAM  usage. It would be nice to be able to apply this configuration without going into the Docker container and editing the config after each update.

**Comment by rychardeh** [comment]
As an end user I've had the same problem.  I believe you can set store-enabled with the recent changes to use environment variables, e.g.:
```
auth: true
reporting: true
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
envvars:
  - name: INFLUXDB_MONITOR_STORE_ENABLED
    value: 'false'
log_level: info
```
My more pressing problem was it running out of memory during compaction which I couldn't fix with any influxdb option.  As I've [commented previously](https://github.com/hassio-addons/addon-influxdb/issues/53#issuecomment-564007959) on issue 53 it seems that influxdb just isn't going to cut it as a long-term solution on an RPI.  I've reluctantly moved influxdb to a different machine for data collection.

**Comment by L2v2P** [comment]
If this works, then this issue can be closed. @rychardeh I've tried compacting, but could issue a command that works. Which one did you use?

**Comment by rychardeh** [comment]
I'm not sure I follow what you mean by command.  Influxdb just compacts at boot time if the DB needs it and periodically thereafter - I don't know if there is a way to trigger it manually.

**Comment by L2v2P** [comment]
Ah, I see. I was looking at https://docs.influxdata.com/influxdb/v1.8/administration/compact-series-file/. But that doesn't work either it seems. Thanks.

**Comment by L2v2P** [comment]
I tried it on the default addon container.

**Comment by L2v2P** [comment]
Possible to do this via environment variables.
