### ISSUE TITLE
I could not install?

### ISSUE THREAD

**Issue by hoanglongutc** [hassio-addons/addon-influxdb#79]
My log shows the following error:
ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install hassioaddons/influxdb-amd64:3.6.2 -> 404 Client Error: Not Found ("no such image: hassioaddons/influxdb-amd64:3.6.2: No such image: hassioaddons/influxdb-amd64:3.6.2").

I can send you the information below:

root@HA:~# df -h
Filesystem Size Used Avail Use% Mounted on
udev 1.6G 0 1.6G 0% /dev
tmpfs 325M 34M 291M 11% /run
/dev/sda1 143G 5.8G 130G 5% /
tmpfs 1.6G 0 1.6G 0% /dev/shm
tmpfs 5.0M 4.0K 5.0M 1% /run/lock
tmpfs 1.6G 0 1.6G 0% /sys/fs/cgroup
overlay 143G 5.8G 130G 5% /var/lib/docker/overlay2/133cddb0b2625ddcb7dfa17aef27aba6585546a64a62d3db01c0f6f3b522bb23/merged
overlay 143G 5.8G 130G 5% /var/lib/docker/overlay2/bf83908aa80880f79d95d2484d48e65613597a207c51a1ce7e5ec6cd7ff321f4/merged
overlay 143G 5.8G 130G 5% /var/lib/docker/overlay2/de27b4384c61c3e260063fcd26374b789b71a675e896873fdce67d944d5214b6/merged
overlay 143G 5.8G 130G 5% /var/lib/docker/overlay2/e06924495c5b678bc98a7da8fc57b3442a29ebcdf35b50a47571334cc3196f7a/merged
overlay 143G 5.8G 130G 5% /var/lib/docker/overlay2/bee406297c7cb350be7c40ab29866d5d7726629b96ad669642f26cc0a1c2a244/merged
overlay 143G 5.8G 130G 5% /var/lib/docker/overlay2/e1e3ffe967aa4f9c2e58e33548161e890476d143ad5d6703f908fe312caa26c3/merged
overlay 143G 5.8G 130G 5% /var/lib/docker/overlay2/32f21e28ca969f915d5e59a168b54bb6923f2d6e3df9b2ef790bc726e14279bc/merged
tmpfs 325M 0 325M 0% /run/user/0

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/82892117-30e88900-9f4f-11ea-8aa8-47094253a438.png)

https://hub.docker.com/r/hassioaddons/influxdb-amd64/tags?page=1&name=3.6.2

It exists, the problem relies on your system. Sorry m8.
