### ISSUE TITLE
ERROR (SyncWorker_16) [supervisor.docker.interface] Can't install hassioaddons/influxdb-armv7:3.7.1 -> 404 Client Error: Not Found ("no such image: hassioaddons/influxdb-armv7:3.7.1: No such image: hassioaddons/influxdb-armv7:3.7.1").

### ISSUE THREAD

**Issue by 0michalsokolowski0** [hassio-addons/addon-influxdb#82]
# Problem/Motivation

> Cannot install the addon and there is an error in logs `ERROR (SyncWorker_16) [supervisor.docker.interface] Can't install hassioaddons/influxdb-armv7:3.7.1 -> 404 Client Error: Not Found ("no such image: hassioaddons/influxdb-armv7:3.7.1: No such image: hassioaddons/influxdb-armv7:3.7.1").`

## Expected behavior

> Addon installs correctly

## Actual behavior

> Addon has not been installed

## Steps to reproduce

>Click install Addon in the Web UI

Raspberry PI 3B+

**Comment by frenck** [comment]
404 = Not enough diskspace available to complete the operation.
