### ISSUE TITLE
Kapacitor does not run on aarch64 machine

### ISSUE THREAD

**Issue by 8illy8o8** [hassio-addons/addon-influxdb#83]
# Problem/Motivation
The InfluxDB add-on, in Home Assistant 110.4 will not start. Has been the case since long before version 100.

## Expected behavior
Should run without error

## Actual behavior
Kapacitor fails to start with the error
./run: line 33: /usr/bin/kapacitord: cannot execute binary file: Exec format error

## Steps to reproduce
Attempt to run InfluxDB add-on on a ARM64 (aarch64) machine. In my case this is an S905X android box. This is exactly the same issue as previously posted and unresolved.

## Proposed changes
I am happy to reconfigure and test as instructed.

LOG file:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: InfluxDB
 Scalable datastore for metrics, events, and real-time analytics
-----------------------------------------------------------
 Add-on version: 3.7.1
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.4 LTS  (aarch64 / qemuarm-64)
 Home Assistant Core: 0.110.4
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] create-users.sh: executing... 
[cont-init.d] create-users.sh: exited 0.
[cont-init.d] influxdb.sh: executing... 
[cont-init.d] influxdb.sh: exited 0.
[cont-init.d] kapacitor.sh: executing... 
[cont-init.d] kapacitor.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:01:23] INFO: Starting the InfluxDB...
[10:01:23] INFO: Chronograf is waiting until InfluxDB is available...
[10:01:23] INFO: Kapacitor is waiting until InfluxDB is available...
[10:01:55] INFO: Starting the Kapacitor
[10:01:55] INFO: Starting Chronograf...
./run: line 33: /usr/bin/kapacitord: cannot execute binary file: Exec format error
./run: line 33: /usr/bin/kapacitord: Success
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by sinclairpaul** [comment]
Please see #65
