### ISSUE TITLE
TSM and Memory consumption ?

### ISSUE THREAD

**Issue by aladin2000** [hassio-addons/addon-influxdb#85]
# Problem/Motivation 
Memory consumption 

> (Why the issue was filed)

## Expected behavior
gain on memory consumption ?

> (What you expected to happen)
less memory usage 

## Actual behavior
Slow response time and crash on raspberry PI3

> (What actually happened)
Memory is very Hgh ( 50%) 
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
TSI instead of TSM ?

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
https://www.influxdata.com/blog/how-to-overcome-memory-usage-challenges-with-the-time-series-index/ 

is it that thing to integrate into ? 

sudo docker run -itd --name influx-db --restart unless-stopped \
-e INFLUXDB_DATA_INDEX_VERSION="tsi1" \
-v $PWD:/var/lib/influxdb \
-p 8086:8086 -p 8083:8083 \
influxdb 

<blockquote><img src="https://www.influxdata.com/wp-content/uploads/og-1.png" width="48" align="right"><div><img src="https://www.influxdata.com/wp-content/uploads/Favicon-blue-200x200.png" height="14"> InfluxData</div><div><strong><a href="https://www.influxdata.com/blog/how-to-overcome-memory-usage-challenges-with-the-time-series-index/">How to Overcome Memory Usage Challenges with the Time Series Index | Blog | InfluxData</a></strong></div><div>For optimum performance and RAM usage, InfluxData introduced a special indexing mechanism for InfluxDB called time series index (TSI). TSI optimizes the RAM usage saturation for larger data sets.</div></blockquote>

**Comment by frenck** [comment]
You can override any setting as you wish:

<https://github.com/hassio-addons/addon-influxdb/blob/master/influxdb/DOCS.md#option-envvars>
