### ISSUE TITLE
InfluxDB host from documentation is not always correct

### ISSUE THREAD

**Issue by boxcee** [hassio-addons/addon-influxdb#86]
# Problem/Motivation
When I installed InfluxDB addon, HA was not enable to connect because the host settings from the documentation were wrong.

## Expected behavior
Better explanation where the host settings are defined/coming from.

## Actual behavior
When installing InfluxDB, I set the host for the HA integration to the host mentioned in the documentation. This host however was wrong for me.

I found the correct host by running `ha supervisor info` and comparing the slug/repository keys of my addons. The host from the documentation matched the slug/repository of AdGuard and WireGuard, but not InfluxDB.

```addons:
- description: Fast, modern, secure VPN tunnel
  icon: false
  installed: 0.3.2
  logo: false
  name: WireGuard
  repository: a0d7b954
  slug: a0d7b954_wireguard
  state: started
  version: 0.3.2
- description: Network-wide ads & trackers blocking DNS server
  icon: false
  installed: 2.4.2
  logo: false
  name: AdGuard Home
  repository: a0d7b954
  slug: a0d7b954_adguard
  state: started
  version: 2.4.2
- description: The open platform for beautiful analytics and monitoring
  icon: true
  installed: 5.2.1
  logo: true
  name: Grafana
  repository: ccf28a08
  slug: ccf28a08_grafana
  state: started
  version: 5.2.1
- description: Scalable datastore for metrics, events, and real-time analytics
  icon: true
  installed: 3.7.3
  logo: true
  name: InfluxDB
  repository: ccf28a08
  slug: ccf28a08_influxdb
  state: started
  version: 3.7.3
```
Changing the host to `ccf28a08-influxdb` instead of `a0d7b954-influxdb` fixed it for me.

## Steps to reproduce
Not entirely sure, to be honest. I would say:

Install AdGuard, install WireGuard, install InfluxDB.

## Proposed changes
I don't really understand how the host is configured and how the supervisor works etc., but I propose to improve the documentation a bit for that case.

**Comment by frenck** [comment]
Not sure where you've got the add-on for, but `ccf28a08` is not this repository.
Therefore, the add-on you are running there is not this one (maybe a forked one?) and thus the documentation does indeed not match, as well, not this add-on.

**Comment by boxcee** [comment]
@frenck not sure where I made a mistake though.

Here is a screenshot from the info view for the addon: https://imgur.com/gallery/zxJQmpe.

**Comment by boxcee** [comment]
I understand what I did wrong. I added the community addons repository twice! And then removed the first one apparently.

**Comment by boxcee** [comment]
Okay, that was not the issue.

Got some help from @ludeeus.

Tried to run this from the browser dev-tools:
```
document.querySelector("home-assistant").hass.callApi("GET", "hassio/supervisor/info").then(e => {console.log(e.data.addons_repositories)})
```
which yielded:
```
["https://github.com/hassio-addons/repository.git", "https://github.com/hassio-addons/repository"]
```
Deleting the first one (`supervisor`->`addons`->`repositories`) puts everything into the right place again.
