### ISSUE TITLE
Request: Clarity on how to graph true/false or home/not home

### ISSUE THREAD

**Issue by Joshfindit** [hassio-addons/addon-influxdb#87]
# Problem/Motivation

Looking for a time-series of when a generic bool sensor was true/false

## Expected behavior

- Explore homeassistant.autogen
- Find the right data type (which I thought would be bool, but this is my first experience with Influx/Grafana, so who knows)
- Graph true/false

## Actual behavior

I got confused

## Proposed changes

Document some common queries
- Getting a true/false sensor
- Home/away sensors
- Download/Upload speed (good trick here for any newbies: set Unit to the actual units reported, not the scale you want the graph in)
- Ping latency (actually super easy as the ms datatype automatically graphs all entries on the same graph)
- Etc

Thank you

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
