### ISSUE TITLE
I don’t see my sensor  ....

### ISSUE THREAD

**Issue by belidi** [hassio-addons/addon-influxdb#89]
Hello,
I installed grafana and infuxdb (v 3.7.5) via supervisor and followed the instructions given in the documentation. But I don’t see my sensors and I have the following message in the log: "Cannot connect to InfluxDB due to ‘HTTPConnectionPool (host =’ aod7b954-influxdb ‘, port = 8086): Max retries exceeded with url: / write? db = homeassistant (Caused by NewConnectionError (’<urllib3.connection.HTTPConnection object at 0x99f749a0>: Failed to establish a new connection: [Errno -3] Try again’)) '. Please check that the provided connection details (host, port , etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds. "
What can I do ?
thanks for the help

**Comment by sinclairpaul** [comment]
`aod7b954`

Should be:

`a0d7b954`

I'm assuming you have the letter o rather than a zero.

**Comment by belidi** [comment]
Great, Thank Y
