### ISSUE TITLE
No such image: hassioaddons/influxdb-amd64:3.7.9

### ISSUE THREAD

**Issue by harishpillay** [hassio-addons/addon-influxdb#93]
# Problem/Motivation

I can't figure out why influxdb is not found. I've a brand new installation of home assistant 2020.11 and tried to install the inluxDB to work with related tools to do mqtt.

## Expected behavior
Should have successfully installed.
## Actual behavior
Gives the error "404 Client Error: Not Found ("no such image: hassioaddons/influxdb-amd64:3.7.9: No such image: hassioaddons/influxdb-amd64:3.7.9")
## Steps to reproduce
Fresh install of home assistant (this is a VM image for KVM)
Try to install influxDB and it fails.
## Proposed changes
Not sure what to propose.

**Comment by sinclairpaul** [comment]
The image exists, so the issue is likely local to you.

Check the supervisor logs for errors.

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/100266694-82032500-2f52-11eb-933a-97ce5c593742.png)


<https://hub.docker.com/layers/hassioaddons/influxdb-amd64/3.7.9/images/sha256-662b9559239ccd1ae5be72cd8e89a821184222f9f600a0ee00ff8bc3c89dd05d?context=explore>


Make sure you have not reached your daily pull limit and have enough disk space available.

**Comment by harishpillay** [comment]
Thank you. I will check.

**Comment by harishpillay** [comment]
Yes, it is indeed a local issue. It has to do with disk space in the VM. Thanks. I now need to increase the VMs size.
