### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by MrM-NL** [hassio-addons/addon-influxdb#95]
# Problem/Motivation

Installation fails.

## Expected behavior

Install successfully 

## Actual behavior

Got following error during installation:

20-12-19 11:44:19 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install hassioaddons/influxdb-aarch64:3.7.9 -> 500 Server Error for http+docker://localhost/v1.40/images/create?tag=3.7.9&fromImage=hassioaddons%2Finfluxdb-aarch64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: no such host").

## Steps to reproduce

Install add on
Note: installed on home assistant OS 5.8 stable 
HW: rpi 4 2GB ram
Boot from  ssd 

## Proposed changes

> fix please.

**Comment by frenck** [comment]
`"Get "registry-1.docker.io/v2": dial tcp: lookup registry-1.docker.io: no such host"`
That is an issue with your system or network and outside of the control from an add-on perspective.

**Comment by MrM-NL** [comment]
Thanks for investigate. Would please can elaborate? I’ve not done any install or modification manually.
Regards.
merry Xmas :-)

**Comment by MrM-NL** [comment]
Just tried and it just installed with no issues. :-/
Thanks again.

**Comment by frenck** [comment]
Happy Holidays 🎄

**Comment by MrM-NL** [comment]
You too.
