### ISSUE TITLE
Influx DB high CPU usage ond RPi4

### ISSUE THREAD

**Issue by Kosygor** [hassio-addons/addon-influxdb#96]
# Problem/Motivation

My setup:
RPI 4 running Home assistant 2020.12.0 in docket with Supervisior 2020.12.7 Influx DB 3.7.9
Running 3 databases _internal/glances/home assistant which last of them has 3 retention policies with 50 CQ running for down sampling data.
Downgrading with snapshot will not work for me because last copy of it is younger than problem occurred.

After stopping Influx Addon CPU usage drops to 12-15 %

I have tried to removing glaces addon and use #81 solutions but nothing affected CPU usage.

## Expected behavior

I am expecting to cut down procesor usage since there is litte left. 

## Actual behavior

CPU rose on 23 OCT from 20% to 80% witch I am  99% sure that not HA or  Influx Itself ware updated.

## Steps to reproduce

I can`t figure any since i was not playing with HA for 2 months.

## Proposed changes

Add UI button for saving database and config(?)

**Comment by frenck** [comment]
From an add-on perspective, there is nothing I can do. This is what it takes and matches your use. If you want to squeeze more out of it, you'll need more powerful hardware.
