### ISSUE TITLE
influx issue

### ISSUE THREAD

**Issue by saniho** [hassio-addons/addon-influxdb#98]
# Problem/Motivation

> 
  File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 331, in write
    data = make_lines(data, precision).encode('utf-8')
  File "/usr/local/lib/python3.8/site-packages/influxdb/line_protocol.py", line 156, in make_lines
    for field_key, field_value in sorted(iteritems(point['fields'])):
TypeError: '<' not supported between instances of 'int' and 'str'

## Expected behavior

> use influx from Ha

## Actual behavior

> incident au startup

## Steps to reproduce

> can provide log

## Proposed changes
N/A

**Comment by frenck** [comment]
That looks like an error from the Home Assistant logs. Please report your issue with Home Assistant in that case.
